-- WP-050 catalog core, ComponentMap, coverage flags, interim signed table, SKUs.
-- Unapplied until a D18 stack-grant names this checkout. Number 0033 is WP-048, not catalog.
CREATE SCHEMA IF NOT EXISTS catalog;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_catalog') THEN
    CREATE ROLE module_catalog NOLOGIN;
  END IF;
END $roles$;
GRANT module_catalog TO practicehub_app;
GRANT USAGE ON SCHEMA catalog TO module_catalog;

CREATE TABLE IF NOT EXISTS catalog.signed_coverage_table (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  table_version_ref text NOT NULL,
  signer_ref text NOT NULL,
  canonical_sha256 text NOT NULL CHECK (canonical_sha256 ~ '^[0-9a-f]{64}$'),
  flags jsonb NOT NULL CHECK (jsonb_typeof(flags) = 'array' AND jsonb_array_length(flags) > 0),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, table_version_ref)
);

CREATE TABLE IF NOT EXISTS catalog.coverage_flag (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  payer_ref text NOT NULL,
  sku_ref text NOT NULL CHECK (sku_ref ~ '^sku:[a-z0-9][a-z0-9-]{7,63}$'),
  table_version_ref text NOT NULL,
  classification text NOT NULL CHECK (classification IN ('covered','non-covered','unclassified')),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, payer_ref, sku_ref, table_version_ref),
  FOREIGN KEY (tenant_id, table_version_ref) REFERENCES catalog.signed_coverage_table (tenant_id, table_version_ref)
);

CREATE TABLE IF NOT EXISTS catalog.component_map (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  map_version_ref text NOT NULL,
  sku_ref text NOT NULL CHECK (sku_ref ~ '^sku:[a-z0-9][a-z0-9-]{7,63}$'),
  lines jsonb NOT NULL CHECK (jsonb_typeof(lines) = 'array' AND jsonb_array_length(lines) > 0),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, sku_ref, map_version_ref)
);

CREATE TABLE IF NOT EXISTS catalog.catalog_offer (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  offer_version_ref text NOT NULL,
  catalog_version_ref text NOT NULL,
  sku_ref text NOT NULL CHECK (sku_ref ~ '^sku:[a-z0-9][a-z0-9-]{7,63}$'),
  payer_ref text NOT NULL,
  map_version_ref text NOT NULL,
  coverage_table_version_ref text NOT NULL,
  billed_component_refs jsonb NOT NULL CHECK (jsonb_typeof(billed_component_refs) = 'array' AND jsonb_array_length(billed_component_refs) > 0),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0 AND amount_minor <= 9007199254740991),
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, offer_version_ref),
  FOREIGN KEY (tenant_id, sku_ref, map_version_ref) REFERENCES catalog.component_map (tenant_id, sku_ref, map_version_ref),
  FOREIGN KEY (tenant_id, coverage_table_version_ref) REFERENCES catalog.signed_coverage_table (tenant_id, table_version_ref)
);

GRANT SELECT, INSERT ON catalog.signed_coverage_table, catalog.coverage_flag, catalog.component_map, catalog.catalog_offer TO module_catalog;
REVOKE UPDATE, DELETE ON catalog.signed_coverage_table, catalog.coverage_flag, catalog.component_map, catalog.catalog_offer FROM module_catalog;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE catalog.catalog_offer ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.catalog_offer FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.catalog_offer;
CREATE POLICY tenant_isolation ON catalog.catalog_offer
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE catalog.component_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.component_map FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.component_map;
CREATE POLICY tenant_isolation ON catalog.component_map
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE catalog.coverage_flag ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.coverage_flag FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.coverage_flag;
CREATE POLICY tenant_isolation ON catalog.coverage_flag
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE catalog.signed_coverage_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.signed_coverage_table FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.signed_coverage_table;
CREATE POLICY tenant_isolation ON catalog.signed_coverage_table
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'catalog'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('catalog_offer', 'component_map', 'coverage_flag', 'fee_schedule_rate', 'gfe_line', 'good_faith_estimate', 'signed_coverage_table'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema catalog: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
