-- WP-051 Good Faith Estimate tables: PFS/CLFS rates, estimate header, attributed lines.
-- Number 0061 sorts after 0037. The 0037 coverage guard already names these tables.
CREATE TABLE IF NOT EXISTS catalog.fee_schedule_rate (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  schedule text NOT NULL CHECK (schedule IN ('PFS', 'CLFS')),
  schedule_version_ref text NOT NULL CHECK (schedule_version_ref ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  code text NOT NULL CHECK (code ~ '^[0-9A-Z]{5}$'),
  unit_amount_minor bigint NOT NULL CHECK (unit_amount_minor >= 0 AND unit_amount_minor <= 9007199254740991),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, schedule, schedule_version_ref, code)
);

CREATE TABLE IF NOT EXISTS catalog.good_faith_estimate (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  gfe_ref text NOT NULL CHECK (gfe_ref ~ '^gfe:[a-z0-9][a-z0-9-]{7,63}$'),
  subject_ref text NOT NULL CHECK (subject_ref ~ '^subject:[a-z0-9][a-z0-9-]{7,63}$'),
  convening_party_kind text NOT NULL CHECK (convening_party_kind IN ('provider', 'facility')),
  convening_party_ref text NOT NULL CHECK (convening_party_ref ~ '^party:[a-z0-9][a-z0-9-]{7,63}$'),
  pfs_version_ref text NOT NULL CHECK (pfs_version_ref ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  clfs_version_ref text NOT NULL CHECK (clfs_version_ref ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  gfe_total_minor bigint NOT NULL CHECK (gfe_total_minor > 0 AND gfe_total_minor <= 9007199254740991),
  claim_total_minor bigint NOT NULL CHECK (claim_total_minor >= 0 AND claim_total_minor <= 9007199254740991),
  currency text NOT NULL CHECK (currency = 'USD'),
  record_class text NOT NULL CHECK (record_class = 'gfe-record'),
  content_sha256 text NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, gfe_ref)
);

CREATE TABLE IF NOT EXISTS catalog.gfe_line (
  tenant_id text NOT NULL,
  gfe_ref text NOT NULL,
  line_ref text NOT NULL CHECK (line_ref ~ '^line:[a-z0-9][a-z0-9-]{7,63}$'),
  schedule text NOT NULL CHECK (schedule IN ('PFS', 'CLFS')),
  code text NOT NULL CHECK (code ~ '^[0-9A-Z]{5}$'),
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_amount_minor bigint NOT NULL CHECK (unit_amount_minor >= 0 AND unit_amount_minor <= 9007199254740991),
  expected_amount_minor bigint NOT NULL CHECK (
    expected_amount_minor = unit_amount_minor * quantity
    AND expected_amount_minor <= 9007199254740991
  ),
  coverage text NOT NULL CHECK (coverage IN ('covered', 'non-covered')),
  party_kind text NOT NULL CHECK (party_kind IN ('provider', 'facility')),
  party_ref text NOT NULL CHECK (party_ref ~ '^party:[a-z0-9][a-z0-9-]{7,63}$'),
  party_role text NOT NULL CHECK (
    (party_role = 'convening' AND party_kind IN ('provider', 'facility'))
    OR (party_role = 'co-provider' AND party_kind = 'provider')
    OR (party_role = 'co-facility' AND party_kind = 'facility')
  ),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, gfe_ref, line_ref),
  FOREIGN KEY (tenant_id, gfe_ref) REFERENCES catalog.good_faith_estimate (tenant_id, gfe_ref)
);

GRANT SELECT, INSERT ON catalog.fee_schedule_rate, catalog.good_faith_estimate, catalog.gfe_line TO module_catalog;
REVOKE UPDATE, DELETE ON catalog.fee_schedule_rate, catalog.good_faith_estimate, catalog.gfe_line FROM module_catalog;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE catalog.fee_schedule_rate ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.fee_schedule_rate FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.fee_schedule_rate;
CREATE POLICY tenant_isolation ON catalog.fee_schedule_rate
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE catalog.gfe_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.gfe_line FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.gfe_line;
CREATE POLICY tenant_isolation ON catalog.gfe_line
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE catalog.good_faith_estimate ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.good_faith_estimate FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.good_faith_estimate;
CREATE POLICY tenant_isolation ON catalog.good_faith_estimate
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'catalog'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('catalog_offer', 'component_map', 'coverage_flag', 'fee_schedule_rate', 'gfe_line', 'good_faith_estimate', 'signed_coverage_table'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema catalog: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
