-- WP-126 tenant-2 white-label. Unapplied. Simulated isolation proof.
CREATE SCHEMA IF NOT EXISTS tenant_white_label;

DO $roles$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_tenant_white_label') THEN
    CREATE ROLE module_tenant_white_label NOLOGIN;
  END IF;
END
$roles$;
GRANT module_tenant_white_label TO practicehub_app;
GRANT USAGE ON SCHEMA tenant_white_label TO module_tenant_white_label;

CREATE TABLE IF NOT EXISTS tenant_white_label.profile (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  wordmark text NOT NULL,
  primary_color text NOT NULL,
  timezone text NOT NULL,
  fax_cover_ref text NOT NULL,
  letterhead_ref text NOT NULL,
  fax_number_ref text NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic = true),
  PRIMARY KEY (tenant_id)
);

GRANT SELECT, INSERT, UPDATE ON tenant_white_label.profile TO module_tenant_white_label;

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE tenant_white_label.profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_white_label.profile FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON tenant_white_label.profile;
CREATE POLICY tenant_isolation ON tenant_white_label.profile
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'tenant_white_label'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('profile'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema tenant_white_label: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
