-- WP-073 reviews: sentiment-blind invites, public responses, private PHI holds.
CREATE SCHEMA IF NOT EXISTS reviews;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_reviews') THEN
    CREATE ROLE module_reviews NOLOGIN;
  END IF;
END $roles$;
GRANT module_reviews TO practicehub_app;
GRANT USAGE ON SCHEMA reviews TO module_reviews;

CREATE TABLE IF NOT EXISTS reviews.review_invite (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  invite_ref text NOT NULL CHECK (invite_ref ~ '^invite:[a-z0-9][a-z0-9-]{7,63}$'),
  visit_ref text NOT NULL CHECK (visit_ref ~ '^visit:[a-z0-9][a-z0-9-]{7,63}$'),
  location_ref text NOT NULL CHECK (location_ref ~ '^location:[a-z0-9][a-z0-9-]{7,63}$'),
  provider_ref text NOT NULL CHECK (provider_ref ~ '^provider:[a-z0-9][a-z0-9-]{7,63}$'),
  source_package_id text NOT NULL CHECK (source_package_id = 'WP-044'),
  source_ref text NOT NULL CHECK (source_ref = 'placeholder:wp-044-review-invite-source'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, invite_ref)
);

CREATE TABLE IF NOT EXISTS reviews.review_response (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  response_ref text NOT NULL CHECK (response_ref ~ '^response:[a-z0-9][a-z0-9-]{7,63}$'),
  invite_ref text NOT NULL,
  body text NOT NULL CHECK (body !~ '\m\d{3}-\d{2}-\d{4}\M' AND body !~* '\mMRN\M' AND body !~* '\mDOB\M'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, response_ref),
  FOREIGN KEY (tenant_id, invite_ref) REFERENCES reviews.review_invite (tenant_id, invite_ref)
);

CREATE TABLE IF NOT EXISTS reviews.review_private_hold (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  response_ref text NOT NULL CHECK (response_ref ~ '^response:[a-z0-9][a-z0-9-]{7,63}$'),
  invite_ref text NOT NULL,
  body text NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, response_ref),
  FOREIGN KEY (tenant_id, invite_ref) REFERENCES reviews.review_invite (tenant_id, invite_ref)
);

GRANT SELECT, INSERT ON reviews.review_invite, reviews.review_response, reviews.review_private_hold TO module_reviews;
REVOKE UPDATE, DELETE ON reviews.review_invite, reviews.review_response, reviews.review_private_hold FROM module_reviews;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE reviews.review_invite ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews.review_invite FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON reviews.review_invite;
CREATE POLICY tenant_isolation ON reviews.review_invite
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE reviews.review_private_hold ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews.review_private_hold FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON reviews.review_private_hold;
CREATE POLICY tenant_isolation ON reviews.review_private_hold
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE reviews.review_response ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews.review_response FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON reviews.review_response;
CREATE POLICY tenant_isolation ON reviews.review_response
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'reviews'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('review_invite', 'review_private_hold', 'review_response'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema reviews: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
