-- WP-056 ledger API v2. Three rails, penny payout drift, write-off tiers.
ALTER TABLE payments_ledger.journal
  ADD COLUMN IF NOT EXISTS rail text NOT NULL DEFAULT 'cash';
ALTER TABLE payments_ledger.journal
  DROP CONSTRAINT IF EXISTS journal_rail;
ALTER TABLE payments_ledger.journal
  ADD CONSTRAINT journal_rail CHECK (rail IN ('insurance', 'membership', 'cash'));
ALTER TABLE payments_ledger.journal
  ADD COLUMN IF NOT EXISTS payout_ref text;
ALTER TABLE payments_ledger.journal
  DROP CONSTRAINT IF EXISTS journal_payout_rail;
ALTER TABLE payments_ledger.journal
  ADD CONSTRAINT journal_payout_rail CHECK (payout_ref IS NULL OR rail = 'cash');

CREATE TABLE IF NOT EXISTS payments_ledger.write_off (
  tenant_id text NOT NULL,
  write_off_id text NOT NULL,
  journal_id text NOT NULL,
  reason text NOT NULL CHECK (reason IN ('contractual-adjustment', 'small-balance', 'uncollectible', 'charity')),
  role text NOT NULL CHECK (role IN ('billing-clerk', 'billing-supervisor', 'rcm-lead')),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0 AND amount_minor <= 9007199254740991),
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, write_off_id),
  FOREIGN KEY (tenant_id, journal_id) REFERENCES payments_ledger.journal (tenant_id, journal_id),
  CHECK (
    (reason = 'small-balance' AND amount_minor <= 1000)
    OR (reason = 'contractual-adjustment' AND (
      (role = 'billing-clerk' AND amount_minor <= 1000)
      OR (role = 'billing-supervisor' AND amount_minor <= 10000)
      OR role = 'rcm-lead'))
    OR (reason = 'uncollectible' AND (
      (role = 'billing-supervisor' AND amount_minor <= 10000)
      OR role = 'rcm-lead'))
    OR (reason = 'charity' AND role = 'rcm-lead')
  )
);

CREATE TABLE IF NOT EXISTS payments_ledger.payout_drift_work_item (
  tenant_id text NOT NULL,
  payout_ref text NOT NULL,
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  ledger_minor bigint NOT NULL,
  payout_minor bigint NOT NULL CHECK (payout_minor >= 0 AND payout_minor <= 9007199254740991),
  drift_minor bigint NOT NULL CHECK (drift_minor <> 0 AND drift_minor = payout_minor - ledger_minor),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, payout_ref, currency)
);

GRANT SELECT, INSERT ON payments_ledger.write_off, payments_ledger.payout_drift_work_item TO module_payments_ledger;
REVOKE UPDATE, DELETE ON payments_ledger.write_off, payments_ledger.payout_drift_work_item FROM module_payments_ledger;

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE payments_ledger.payout_drift_work_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments_ledger.payout_drift_work_item FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON payments_ledger.payout_drift_work_item;
CREATE POLICY tenant_isolation ON payments_ledger.payout_drift_work_item
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE payments_ledger.write_off ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments_ledger.write_off FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON payments_ledger.write_off;
CREATE POLICY tenant_isolation ON payments_ledger.write_off
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'payments_ledger'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('credit_balance_clock', 'dunning_account', 'journal', 'journal_line', 'payment_intent', 'payout_drift_work_item', 'statement', 'write_off'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema payments_ledger: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
