-- WP-057 statements, dunning, and credit-balance clocks. Append-only.
CREATE TABLE IF NOT EXISTS payments_ledger.dunning_account (
  tenant_id text NOT NULL,
  account_ref text NOT NULL,
  deceased boolean NOT NULL,
  dunning text NOT NULL CHECK (dunning IN ('active', 'stopped')),
  stopped_reason text CHECK (stopped_reason IS NULL OR stopped_reason = 'deceased'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, account_ref),
  CHECK (NOT deceased OR dunning = 'stopped')
);

CREATE TABLE IF NOT EXISTS payments_ledger.credit_balance_clock (
  tenant_id text NOT NULL,
  clock_id text NOT NULL,
  account_ref text NOT NULL,
  obligation_type text NOT NULL CHECK (obligation_type = 'credit-balance'),
  triggered_at timestamptz NOT NULL,
  due_at timestamptz NOT NULL,
  duration_days integer NOT NULL CHECK (duration_days = 60),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0 AND amount_minor <= 9007199254740991),
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, clock_id)
);

CREATE TABLE IF NOT EXISTS payments_ledger.statement (
  tenant_id text NOT NULL,
  statement_id text NOT NULL,
  account_ref text NOT NULL,
  issue_on date NOT NULL,
  guarantor_ref text NOT NULL,
  guarantor_version integer NOT NULL CHECK (guarantor_version > 0),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, statement_id)
);

GRANT SELECT, INSERT ON payments_ledger.dunning_account, payments_ledger.credit_balance_clock, payments_ledger.statement TO module_payments_ledger;
REVOKE UPDATE, DELETE ON payments_ledger.dunning_account, payments_ledger.credit_balance_clock, payments_ledger.statement FROM module_payments_ledger;

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE payments_ledger.credit_balance_clock ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments_ledger.credit_balance_clock FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON payments_ledger.credit_balance_clock;
CREATE POLICY tenant_isolation ON payments_ledger.credit_balance_clock
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE payments_ledger.dunning_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments_ledger.dunning_account FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON payments_ledger.dunning_account;
CREATE POLICY tenant_isolation ON payments_ledger.dunning_account
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE payments_ledger.statement ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments_ledger.statement FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON payments_ledger.statement;
CREATE POLICY tenant_isolation ON payments_ledger.statement
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'payments_ledger'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('credit_balance_clock', 'dunning_account', 'journal', 'journal_line', 'payment_intent', 'payout_drift_work_item', 'statement', 'write_off'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema payments_ledger: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
