-- WP-113 vintage import rehearsals. Unapplied until a stack-grant.
-- Does not rewrite modules/migration (WP-110) or membership-entitlements.
CREATE SCHEMA IF NOT EXISTS vintage_import;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_vintage_import') THEN
    CREATE ROLE module_vintage_import NOLOGIN;
  END IF;
END $roles$;
GRANT module_vintage_import TO practicehub_app;
GRANT USAGE ON SCHEMA vintage_import TO module_vintage_import;

CREATE TABLE IF NOT EXISTS vintage_import.source_snapshot (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  snapshot_id text NOT NULL,
  checksum_sha256 text NOT NULL,
  expected_checksum_sha256 text NOT NULL,
  frozen_at timestamptz NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, snapshot_id)
);

CREATE TABLE IF NOT EXISTS vintage_import.finding (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  finding_id text NOT NULL,
  snapshot_id text NOT NULL,
  code text NOT NULL CHECK (code IN ('CORRUPTED_BASELINE','COHORT_PRICE_DRIFT','MISSING_KEY')),
  severity text NOT NULL CHECK (severity IN ('blocking','warning')),
  record_ref text,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, finding_id),
  FOREIGN KEY (tenant_id, snapshot_id) REFERENCES vintage_import.source_snapshot (tenant_id, snapshot_id)
);

CREATE TABLE IF NOT EXISTS vintage_import.rehearsal_batch (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  batch_id text NOT NULL,
  snapshot_id text NOT NULL,
  applied_count integer NOT NULL CHECK (applied_count >= 0),
  rolled_back boolean NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, batch_id),
  FOREIGN KEY (tenant_id, snapshot_id) REFERENCES vintage_import.source_snapshot (tenant_id, snapshot_id)
);

GRANT SELECT, INSERT ON vintage_import.source_snapshot TO module_vintage_import;
GRANT SELECT, INSERT ON vintage_import.finding TO module_vintage_import;
GRANT SELECT, INSERT ON vintage_import.rehearsal_batch TO module_vintage_import;
REVOKE UPDATE, DELETE ON vintage_import.source_snapshot FROM module_vintage_import;
REVOKE UPDATE, DELETE ON vintage_import.finding FROM module_vintage_import;
REVOKE UPDATE, DELETE ON vintage_import.rehearsal_batch FROM module_vintage_import;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE vintage_import.finding ENABLE ROW LEVEL SECURITY;
ALTER TABLE vintage_import.finding FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON vintage_import.finding;
CREATE POLICY tenant_isolation ON vintage_import.finding
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE vintage_import.rehearsal_batch ENABLE ROW LEVEL SECURITY;
ALTER TABLE vintage_import.rehearsal_batch FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON vintage_import.rehearsal_batch;
CREATE POLICY tenant_isolation ON vintage_import.rehearsal_batch
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE vintage_import.source_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE vintage_import.source_snapshot FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON vintage_import.source_snapshot;
CREATE POLICY tenant_isolation ON vintage_import.source_snapshot
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'vintage_import'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('finding', 'rehearsal_batch', 'source_snapshot'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema vintage_import: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
