-- WP-117 synthetic acquisition rehearsal. Unapplied.
CREATE SCHEMA IF NOT EXISTS acquisition_rehearsal;

DO $roles$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_acquisition_rehearsal') THEN
    CREATE ROLE module_acquisition_rehearsal NOLOGIN;
  END IF;
END
$roles$;
GRANT module_acquisition_rehearsal TO practicehub_app;
GRANT USAGE ON SCHEMA acquisition_rehearsal TO module_acquisition_rehearsal;

CREATE TABLE IF NOT EXISTS acquisition_rehearsal.rehearsal_run (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  run_id text NOT NULL CHECK (run_id ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  panel_id text NOT NULL,
  imported integer NOT NULL,
  cut_over integer NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('ready-20-of-20','failed-cutover','post-freeze-restored')),
  frozen boolean NOT NULL,
  restored boolean NOT NULL,
  rekeyed boolean NOT NULL,
  work_item_id text,
  synthetic boolean NOT NULL CHECK (synthetic = true),
  PRIMARY KEY (tenant_id, run_id)
);

GRANT SELECT, INSERT, UPDATE ON acquisition_rehearsal.rehearsal_run TO module_acquisition_rehearsal;

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE acquisition_rehearsal.rehearsal_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE acquisition_rehearsal.rehearsal_run FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON acquisition_rehearsal.rehearsal_run;
CREATE POLICY tenant_isolation ON acquisition_rehearsal.rehearsal_run
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'acquisition_rehearsal'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('rehearsal_run'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema acquisition_rehearsal: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
