-- WP-065 device calibration and recall-cohort tables. UNAPPLIED.
-- Depends on modules/labs/migrations/0064-labs.sql.
-- Rollback: modules/labs/migrations/0065-labs-device.rollback.sql.

CREATE TABLE IF NOT EXISTS labs.device_calibration (
  tenant_id text NOT NULL CHECK (tenant_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  result_id text NOT NULL CHECK (result_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  device_id text NOT NULL CHECK (device_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  lot_id text NOT NULL CHECK (lot_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  calibrated_at timestamptz NOT NULL,
  calibration_method text NOT NULL CHECK (char_length(calibration_method) BETWEEN 1 AND 200),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, result_id),
  FOREIGN KEY (tenant_id, result_id) REFERENCES labs.lab_result (tenant_id, result_id)
);

CREATE TABLE IF NOT EXISTS labs.device_recall (
  tenant_id text NOT NULL CHECK (tenant_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  recall_id text NOT NULL CHECK (recall_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  device_id text NOT NULL CHECK (device_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  lot_id text NOT NULL CHECK (lot_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  result_id text NOT NULL CHECK (result_id ~ '^[a-z0-9][a-z0-9:._-]{0,127}$'),
  recalled_at timestamptz NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, recall_id, result_id),
  FOREIGN KEY (tenant_id, result_id) REFERENCES labs.lab_result (tenant_id, result_id)
);

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE labs.device_calibration ENABLE ROW LEVEL SECURITY;
ALTER TABLE labs.device_calibration FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON labs.device_calibration;
CREATE POLICY tenant_isolation ON labs.device_calibration
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE labs.device_recall ENABLE ROW LEVEL SECURITY;
ALTER TABLE labs.device_recall FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON labs.device_recall;
CREATE POLICY tenant_isolation ON labs.device_recall
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'labs'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('critical_closure', 'device_calibration', 'device_recall', 'expected_result_age', 'lab_order', 'lab_result'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema labs: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
