-- WP-052 membership accounts, vintages, pause/cancel/win-back. Unapplied until a stack-grant.
-- Does not rewrite membership_entitlements (WP-031). Consume remains WP-053.
CREATE SCHEMA IF NOT EXISTS membership;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_membership') THEN
    CREATE ROLE module_membership NOLOGIN;
  END IF;
END $roles$;
GRANT module_membership TO practicehub_app;
GRANT USAGE ON SCHEMA membership TO module_membership;

CREATE TABLE IF NOT EXISTS membership.account (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  account_id text NOT NULL,
  member_ref text NOT NULL,
  opened_at timestamptz NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, account_id)
);

CREATE TABLE IF NOT EXISTS membership.vintage (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  vintage_id text NOT NULL,
  account_id text NOT NULL,
  offer_ref text NOT NULL,
  price_minor integer NOT NULL CHECK (price_minor >= 0),
  currency text NOT NULL CHECK (char_length(currency) = 3),
  opened_at timestamptz NOT NULL,
  closed_at timestamptz,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, vintage_id),
  FOREIGN KEY (tenant_id, account_id) REFERENCES membership.account (tenant_id, account_id)
);

CREATE TABLE IF NOT EXISTS membership.lifecycle_event (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  event_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('opened','paused','resumed','cancelled','winback')),
  account_id text NOT NULL,
  vintage_id text NOT NULL,
  idempotency_key text NOT NULL,
  occurred_at timestamptz NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, event_id),
  UNIQUE (tenant_id, idempotency_key),
  FOREIGN KEY (tenant_id, account_id) REFERENCES membership.account (tenant_id, account_id),
  FOREIGN KEY (tenant_id, vintage_id) REFERENCES membership.vintage (tenant_id, vintage_id)
);

GRANT SELECT, INSERT ON membership.account TO module_membership;
GRANT SELECT, INSERT ON membership.vintage TO module_membership;
GRANT SELECT, INSERT ON membership.lifecycle_event TO module_membership;
REVOKE UPDATE, DELETE ON membership.account FROM module_membership;
REVOKE UPDATE, DELETE ON membership.vintage FROM module_membership;
REVOKE UPDATE, DELETE ON membership.lifecycle_event FROM module_membership;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE membership.account ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership.account FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON membership.account;
CREATE POLICY tenant_isolation ON membership.account
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE membership.lifecycle_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership.lifecycle_event FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON membership.lifecycle_event;
CREATE POLICY tenant_isolation ON membership.lifecycle_event
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE membership.vintage ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership.vintage FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON membership.vintage;
CREATE POLICY tenant_isolation ON membership.vintage
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'membership'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('account', 'lifecycle_event', 'vintage'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema membership: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
