-- WP-012 synthetic capability seed. Applied by `pnpm local:seed` after module
-- migrations (tables come from
-- modules/platform-core/migrations/0003-capability.sql). Idempotent: events
-- insert with ON CONFLICT DO NOTHING (the log is append-only; re-seeding
-- never rewrites history); grants upsert to the fold of the event log.
--
-- The section between the capability markers is emitted by
-- renderCapabilitySeedSection(capabilityRegistryV1, syntheticCapabilitySeedV1)
-- in @practicehub/platform-core; a drift test compares this file against a
-- fresh emission, and the DB suite folds the seeded events back against the
-- seeded grants (projection sync). Riverbend stays declared `disabled` — the
-- standing opposite-capability-state tenant proof.
-- capability:generated:begin
-- Generated by @practicehub/platform-core renderCapabilitySeedSection from
-- syntheticCapabilitySeedV1. Regenerate on any seed change; the drift test
-- and the DB projection-sync test fail on divergence.
INSERT INTO platform_core.capability_event
  (event_id, tenant_id, capability_id, scope, scope_key, from_state, to_state,
   initiator_ref, approvals, evidence_refs, rollback_ref, review_ref,
   target_capability_id, reason, synthetic)
VALUES
  ('synthetic-cap-evt-0001', 'northwind-synthetic', 'platform.capability-registry', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-012-registry-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0002', 'northwind-synthetic', 'platform.capability-registry', '{}'::jsonb, '(root)', 'scaffolded', 'simulated', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-012-registry-simulated"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0003', 'northwind-synthetic', 'platform.bootstrap', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:plan-000-bootstrap-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0004', 'northwind-synthetic', 'platform.bootstrap', '{}'::jsonb, '(root)', 'scaffolded', 'simulated', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:plan-000-bootstrap-simulated"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0005', 'northwind-synthetic', 'rcm.rail-path', '{"payer":"synthetic-payer-aurora","provider":"synthetic-dr-lee","transaction":"x12-837"}'::jsonb, 'payer=synthetic-payer-aurora/provider=synthetic-dr-lee/transaction=x12-837', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:rail-837-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0006', 'northwind-synthetic', 'rcm.rail-path', '{"payer":"synthetic-payer-aurora","provider":"synthetic-dr-lee","transaction":"x12-837"}'::jsonb, 'payer=synthetic-payer-aurora/provider=synthetic-dr-lee/transaction=x12-837', 'scaffolded', 'simulated', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:rail-837-sim-conformance"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0007', 'northwind-synthetic', 'rcm.rail-path', '{"payer":"synthetic-payer-aurora","provider":"synthetic-dr-lee","transaction":"x12-270-271"}'::jsonb, 'payer=synthetic-payer-aurora/provider=synthetic-dr-lee/transaction=x12-270-271', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:rail-270-271-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0008', 'northwind-synthetic', 'identity.person-model', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-013-identity-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0009', 'northwind-synthetic', 'identity.authn', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-014-authn-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0010', 'northwind-synthetic', 'identity.merge-governance', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-016-merge-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0011', 'northwind-synthetic', 'platform.audit-store', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-020-audit-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0012', 'northwind-synthetic', 'identity.access-policy', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-015-pdp-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0013', 'northwind-synthetic', 'privacy.gipa-partition', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-015-gipa-partition-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0014', 'northwind-synthetic', 'consent.operational', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-018-consent-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0015', 'northwind-synthetic', 'platform.event-spine', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-021-event-spine-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0016', 'northwind-synthetic', 'consent.policy-clocks', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-019-policy-clocks-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true),
  ('synthetic-cap-evt-0017', 'northwind-synthetic', 'platform.tasking-engine', '{}'::jsonb, '(root)', 'disabled', 'scaffolded', 'synthetic-platform-bootstrap', '[{"approverRef":"synthetic-architecture-owner","role":"architecture"}]'::jsonb, '["synthetic-gate:wp-022-tasking-engine-scaffold"]'::jsonb, 'registry-event-replay', NULL, NULL, 'synthetic bootstrap chain', true)
ON CONFLICT (event_id) DO NOTHING;

INSERT INTO platform_core.capability_grant
  (tenant_id, capability_id, scope, scope_key, state, since_event_id,
   evidence_refs, rollback_ref, synthetic)
VALUES
  ('northwind-synthetic', 'consent.operational', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0014', '["synthetic-gate:wp-018-consent-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'consent.policy-clocks', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0016', '["synthetic-gate:wp-019-policy-clocks-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'identity.access-policy', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0012', '["synthetic-gate:wp-015-pdp-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'identity.authn', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0009', '["synthetic-gate:wp-014-authn-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'identity.merge-governance', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0010', '["synthetic-gate:wp-016-merge-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'identity.person-model', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0008', '["synthetic-gate:wp-013-identity-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'platform.audit-store', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0011', '["synthetic-gate:wp-020-audit-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'platform.bootstrap', '{}'::jsonb, '(root)', 'simulated', 'synthetic-cap-evt-0004', '["synthetic-gate:plan-000-bootstrap-simulated"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'platform.capability-registry', '{}'::jsonb, '(root)', 'simulated', 'synthetic-cap-evt-0002', '["synthetic-gate:wp-012-registry-simulated"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'platform.event-spine', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0015', '["synthetic-gate:wp-021-event-spine-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'platform.tasking-engine', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0017', '["synthetic-gate:wp-022-tasking-engine-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'privacy.gipa-partition', '{}'::jsonb, '(root)', 'scaffolded', 'synthetic-cap-evt-0013', '["synthetic-gate:wp-015-gipa-partition-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'rcm.rail-path', '{"payer":"synthetic-payer-aurora","provider":"synthetic-dr-lee","transaction":"x12-270-271"}'::jsonb, 'payer=synthetic-payer-aurora/provider=synthetic-dr-lee/transaction=x12-270-271', 'scaffolded', 'synthetic-cap-evt-0007', '["synthetic-gate:rail-270-271-scaffold"]'::jsonb, 'registry-event-replay', true),
  ('northwind-synthetic', 'rcm.rail-path', '{"payer":"synthetic-payer-aurora","provider":"synthetic-dr-lee","transaction":"x12-837"}'::jsonb, 'payer=synthetic-payer-aurora/provider=synthetic-dr-lee/transaction=x12-837', 'simulated', 'synthetic-cap-evt-0006', '["synthetic-gate:rail-837-sim-conformance"]'::jsonb, 'registry-event-replay', true),
  ('riverbend-synthetic', 'consent.operational', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'consent.policy-clocks', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'identity.access-policy', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'identity.authn', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'identity.merge-governance', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'identity.person-model', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'platform.audit-store', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'platform.bootstrap', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'platform.capability-registry', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'platform.event-spine', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'platform.tasking-engine', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true),
  ('riverbend-synthetic', 'privacy.gipa-partition', '{}'::jsonb, '(root)', 'disabled', NULL, '["synthetic-negative-control"]'::jsonb, 'already-disabled', true)
ON CONFLICT (tenant_id, capability_id, scope_key) DO UPDATE
SET scope = EXCLUDED.scope,
    state = EXCLUDED.state,
    since_event_id = EXCLUDED.since_event_id,
    evidence_refs = EXCLUDED.evidence_refs,
    rollback_ref = EXCLUDED.rollback_ref,
    synthetic = EXCLUDED.synthetic;
-- capability:generated:end
