-- WP-020 synthetic audit-evidence seed. Applied by `pnpm local:seed` after
-- module migrations (tables come from
-- modules/audit-evidence/migrations/0007-audit.sql). Idempotent; synthetic
-- data only. Standing proofs this seed carries:
--   * a Northwind tenant-day hash chain across the streams, including an
--     access DENY (deny paths are audited — R6-REQ-001) and an AI interaction
--     with model + version and prompt/output ref+hash pairs (R6-REQ-102);
--   * a disclosure export carrying a partition tag (tags survive export);
--   * an ACTIVE Northwind legal hold on clinical records (hold suspends
--     destruction) beside executed destruction evidence for an unheld class;
--   * a released Riverbend hold retaining its release evidence, plus a
--     one-link Riverbend chain for the cross-tenant negatives.
-- The section between the audit markers is emitted by
-- renderAuditSeedSection(syntheticAuditSeedV1) in @practicehub/audit-evidence;
-- a drift test compares this file against a fresh emission, and the DB suite
-- recomputes the seeded chains from the stored rows. Audit events and
-- destruction evidence insert with ON CONFLICT DO NOTHING — append-only
-- history is never rewritten by a re-seed.
-- audit:generated:begin
-- Generated by @practicehub/audit-evidence renderAuditSeedSection from
-- syntheticAuditSeedV1. Regenerate on any seed change; the drift test and
-- the DB chain-recompute test fail on divergence.
INSERT INTO audit_evidence.retention_schedule
  (record_class, version, status, basis, fixed_term_years, minimum_years,
   minors_extension, age_of_majority_years, basis_ref, change_control_ref, synthetic)
VALUES
  ('clinical-record', 1, 'draft', 'jurisdiction-resolver', NULL, 5, 'age-of-majority-anchor', 18, 'state-matrix-sec-8-r6-sr-080', 'wp-020-retention-schedule-v1', true),
  ('consent-artifact', 1, 'draft', 'jurisdiction-resolver', NULL, 6, 'age-of-majority-anchor', 18, 'state-matrix-sec-8-consent-follows-record-clock', 'wp-020-retention-schedule-v1', true),
  ('audit-log', 1, 'draft', 'fixed-term', 6, 6, 'none', 18, 'hipaa-45-cfr-164-316-b-2-documentation', 'wp-020-retention-schedule-v1', true),
  ('ai-interaction', 1, 'draft', 'fixed-term', 6, 6, 'none', 18, 'r6-req-102-ai-log-follows-audit-log-clock', 'wp-020-retention-schedule-v1', true),
  ('gfe-record', 1, 'draft', 'fixed-term', 6, 6, 'none', 18, 'r6-req-052-nsa-gfe-45-cfr-149-610', 'wp-020-retention-schedule-v1', true),
  ('disclosure-accounting', 1, 'draft', 'fixed-term', 6, 6, 'none', 18, 'hipaa-45-cfr-164-528-accounting', 'wp-020-retention-schedule-v1', true)
ON CONFLICT (record_class, version) DO UPDATE
SET status = EXCLUDED.status,
    basis = EXCLUDED.basis,
    fixed_term_years = EXCLUDED.fixed_term_years,
    minimum_years = EXCLUDED.minimum_years,
    minors_extension = EXCLUDED.minors_extension,
    age_of_majority_years = EXCLUDED.age_of_majority_years,
    basis_ref = EXCLUDED.basis_ref,
    change_control_ref = EXCLUDED.change_control_ref,
    synthetic = EXCLUDED.synthetic;

INSERT INTO audit_evidence.audit_event
  (tenant_id, audit_id, stream, action, actor_ref, subject_ref, decision,
   reason, source_ref, correlation_ref, recipient_ref, purpose, model_ref,
   model_version, prompt_ref, prompt_hash, output_ref, output_hash, detail,
   partition_tags, chain_day, chain_seq, prev_hash, entry_hash, occurred_at,
   synthetic)
VALUES
  ('northwind-synthetic', 'nae-0001', 'access', 'chart-view', 'synthetic-staff:synthetic-front-desk-001', 'np-sam-porter', 'allow', 'treatment', 'synthetic-device:workstation-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, '{}'::text[], '2026-03-15', 1, 'genesis', '252f13f077539ef3d777dffd9b95094b39e867c624a2d8f0433f98139d33c327', '2026-03-15T09:00:00Z', true),
  ('northwind-synthetic', 'nae-0002', 'access', 'chart-view', 'synthetic-staff:synthetic-front-desk-001', 'np-jordan-kim', 'deny', 'operations', 'synthetic-device:workstation-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, '{}'::text[], '2026-03-15', 2, '252f13f077539ef3d777dffd9b95094b39e867c624a2d8f0433f98139d33c327', 'ef0f3199bfae6edee0939baf273e3f6102599b3c97cfd4b8e7b997d94a5f3f7c', '2026-03-15T09:05:00Z', true),
  ('northwind-synthetic', 'nae-0003', 'ai-interaction', 'draft-message', 'synthetic-staff:synthetic-care-guide-001', 'np-jordan-kim', NULL, NULL, NULL, NULL, NULL, NULL, 'model-sim:claude-sonnet', 'claude-sonnet-5-synthetic', 'minio://synthetic-ai/prompts/nai-0003-prompt', '738febdcb484a8131e487cfc62490ad818f71b47a05bec45602e88b4ac48eafd', 'minio://synthetic-ai/outputs/nai-0003-output', '8af45dca8fa59587fdce76a1c31bb9c98304f2bf4f520510dd7a9953e3e9a798', '{}'::jsonb, '{}'::text[], '2026-03-15', 3, 'ef0f3199bfae6edee0939baf273e3f6102599b3c97cfd4b8e7b997d94a5f3f7c', '754042b55899df540f91ad3683509bca20f98d86bbea9ad3a22c2ea4c1a9a2d1', '2026-03-15T09:20:00Z', true),
  ('northwind-synthetic', 'nae-0004', 'disclosure', 'records-export', 'synthetic-staff:synthetic-compliance-001', 'np-sam-porter', 'allow', NULL, NULL, NULL, 'synthetic-recipient:records-requester-0007', 'patient-request', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, ARRAY['gipa-genetic']::text[], '2026-03-15', 4, '754042b55899df540f91ad3683509bca20f98d86bbea9ad3a22c2ea4c1a9a2d1', 'd160085c4c64dcf0400fa9a39c2e8f8ba51b83c5c2ebe6ff3a5be77d38dfeb5f', '2026-03-15T10:00:00Z', true),
  ('northwind-synthetic', 'nae-0005', 'config-change', 'legal-hold-placed', 'synthetic-staff:synthetic-compliance-001', NULL, NULL, NULL, NULL, 'nlh-0001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"config_ref":"legal-hold:nlh-0001","matter_ref":"synthetic-matter-0001"}'::jsonb, '{}'::text[], '2026-03-15', 5, 'd160085c4c64dcf0400fa9a39c2e8f8ba51b83c5c2ebe6ff3a5be77d38dfeb5f', 'eaedd9c6321d7963b05310d358da8f71e2851cd38a7b5bf56d0562f11c435e9d', '2026-03-15T10:30:00Z', true),
  ('northwind-synthetic', 'nae-0006', 'config-change', 'destruction-executed', 'synthetic-staff:synthetic-compliance-001', NULL, NULL, NULL, NULL, 'nde-0001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"config_ref":"destruction:nde-0001","record_class":"gfe-record","manifest_hash":"fc657949091e29d5944345f2dc0a3217fcaa8713e75a792e4d8e4414b1ea1eb8","authority_ref":"synthetic-staff:synthetic-compliance-001"}'::jsonb, '{}'::text[], '2026-03-15', 6, 'eaedd9c6321d7963b05310d358da8f71e2851cd38a7b5bf56d0562f11c435e9d', 'b5227f3912573237f3477bd3540bf154a9512e54daa6bab426345914d4b37eb9', '2026-03-15T11:00:00Z', true),
  ('northwind-synthetic', 'nae-0007', 'capability-transition', 'capability-transition-recorded', 'synthetic-platform-bootstrap', NULL, NULL, NULL, NULL, 'synthetic-cap-evt-0011', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"capability_id":"platform.audit-store","from_state":"disabled","to_state":"scaffolded"}'::jsonb, '{}'::text[], '2026-03-15', 7, 'b5227f3912573237f3477bd3540bf154a9512e54daa6bab426345914d4b37eb9', 'f6a78fa6568f4e904d14c0e249d541b83101547f8c02882b9af5ca93cc1bc846', '2026-03-15T11:30:00Z', true),
  ('riverbend-synthetic', 'rae-0001', 'access', 'chart-view', 'synthetic-staff:synthetic-front-desk-101', 'rb-taylor-quinn', 'allow', 'treatment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, '{}'::text[], '2026-03-15', 1, 'genesis', 'f00548987c2b1a4a98e0ad964b4d6363f7ad5a0df22e1a0b9ea392dd6b0ed66c', '2026-03-15T09:00:00Z', true)
ON CONFLICT (tenant_id, audit_id) DO NOTHING;

INSERT INTO audit_evidence.legal_hold
  (tenant_id, hold_id, matter_ref, legal_entity_id, record_classes, status,
   placed_by, placed_basis_ref, released_by, release_evidence_ref, synthetic)
VALUES
  ('northwind-synthetic', 'nlh-0001', 'synthetic-matter-0001', NULL, ARRAY['clinical-record']::text[], 'active', 'synthetic-staff:synthetic-compliance-001', 'synthetic-litigation-hold-order-0001', NULL, NULL, true),
  ('riverbend-synthetic', 'rlh-0001', 'synthetic-matter-0101', NULL, '{}'::text[], 'released', 'synthetic-staff:synthetic-compliance-101', 'synthetic-litigation-hold-order-0101', 'synthetic-staff:synthetic-compliance-101', 'synthetic-hold-release-memo-0101', true)
ON CONFLICT (tenant_id, hold_id) DO UPDATE
SET matter_ref = EXCLUDED.matter_ref,
    legal_entity_id = EXCLUDED.legal_entity_id,
    record_classes = EXCLUDED.record_classes,
    status = EXCLUDED.status,
    placed_by = EXCLUDED.placed_by,
    placed_basis_ref = EXCLUDED.placed_basis_ref,
    released_by = EXCLUDED.released_by,
    release_evidence_ref = EXCLUDED.release_evidence_ref,
    synthetic = EXCLUDED.synthetic;

INSERT INTO audit_evidence.destruction_evidence
  (tenant_id, destruction_id, record_class, record_refs, why_basis_refs,
   authority_ref, manifest_hash, audit_id, synthetic)
VALUES
  ('northwind-synthetic', 'nde-0001', 'gfe-record', ARRAY['synthetic-gfe:gfe-legacy-0114']::text[], ARRAY['r6-req-052-nsa-gfe-45-cfr-149-610']::text[], 'synthetic-staff:synthetic-compliance-001', 'fc657949091e29d5944345f2dc0a3217fcaa8713e75a792e4d8e4414b1ea1eb8', 'nae-0006', true)
ON CONFLICT (tenant_id, destruction_id) DO NOTHING;
-- audit:generated:end
