-- WP-015 synthetic PDP seed. Applied by `pnpm local:seed` after module
-- migrations (tables come from modules/identity/migrations/0008-pdp.sql).
-- Idempotent; synthetic data only. Standing proofs this seed carries:
--   * NORTHWIND carries the canonical v1 role templates (generated section
--     below — canonicalRoleTemplateSeedsV1 is the one data source) while
--     RIVERBEND deliberately carries NONE: an unresolvable template is a
--     deny, so tenant 2 is the standing deny-by-default posture proof;
--   * one staff role assignment (it-security-admin: an EMPTY permit set —
--     administration is not data access) plus one justified, approved,
--     TIME-BOXED override flagged for review (REQ-ID-018 AC-7/AC-8/EX-2);
--   * an active guardian-minor authority record over the seeded household
--     minor, scoped and evidenced (REQ-ID-006 AC-1);
--   * a deceased-flagged person: the chart-lock standing proof
--     (REQ-ID-021 — set event carries its confirmation source);
--   * GIPA partition rows: a confirmed genetic tag, a migrated
--     needs-classification-review row BLOCKED from release (EX-1), an
--     active written authorization AND an expired one (the send-time
--     recheck standing pair, EX-2/EX-4).

-- The deceased-flag subject (kept separate from the merge/authn actors so
-- suppression posture never collides with their standing proofs).
INSERT INTO identity.person
  (tenant_id, person_id, status, verification_evidence_ref, birth_date,
   provenance_source, captured_by, consent_ref, synthetic)
VALUES
  ('northwind-synthetic', 'np-riley-fox', 'verified', 'synthetic-idproof-0004', '1948-02-11',
   'synthetic-intake', 'synthetic-front-desk-001', 'synthetic-consent-0004', true)
ON CONFLICT (tenant_id, person_id) DO UPDATE
SET status = EXCLUDED.status,
    verification_evidence_ref = EXCLUDED.verification_evidence_ref,
    birth_date = EXCLUDED.birth_date,
    provenance_source = EXCLUDED.provenance_source,
    captured_by = EXCLUDED.captured_by,
    consent_ref = EXCLUDED.consent_ref,
    synthetic = EXCLUDED.synthetic;

-- pdp:generated:begin
-- Generated by @practicehub/identity renderPdpTemplateSeedSection from
-- canonicalRoleTemplateSeedsV1. Regenerate on any template change; the
-- drift test fails on divergence.
INSERT INTO identity.role_template
  (tenant_id, role_key, version, permits, status, changed_by, change_reason, synthetic)
VALUES
  ('northwind-synthetic', 'front-desk', 1, '[{"segment":"demographics","actions":["view","edit"]},{"segment":"scheduling","actions":["view","edit"]},{"segment":"messaging","actions":["view","edit"]},{"segment":"statements","actions":["view"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'ma-nurse', 1, '[{"segment":"demographics","actions":["view"]},{"segment":"scheduling","actions":["view","edit"]},{"segment":"messaging","actions":["view","edit"]},{"segment":"clinical-notes","actions":["view","edit"]},{"segment":"results","actions":["view"]},{"segment":"medications","actions":["view"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'physician-app', 1, '[{"segment":"demographics","actions":["view"]},{"segment":"scheduling","actions":["view"]},{"segment":"messaging","actions":["view","edit"]},{"segment":"clinical-notes","actions":["view","edit"]},{"segment":"results","actions":["view","edit"]},{"segment":"medications","actions":["view","edit"]},{"segment":"documents","actions":["view","edit"]},{"segment":"genetic","actions":["view","edit"]},{"segment":"confidential-adolescent","actions":["view","edit"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'biller-coder', 1, '[{"segment":"demographics","actions":["view"]},{"segment":"statements","actions":["view","edit"]},{"segment":"payment-methods","actions":["view"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'practice-manager', 1, '[{"segment":"demographics","actions":["view","edit"]},{"segment":"scheduling","actions":["view","edit"]},{"segment":"messaging","actions":["view"]},{"segment":"statements","actions":["view","edit"]},{"segment":"payment-methods","actions":["view"]},{"segment":"documents","actions":["view"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'it-security-admin', 1, '[]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'compliance-privacy-officer', 1, '[{"segment":"demographics","actions":["view"]},{"segment":"documents","actions":["view","export"]},{"segment":"clinical-notes","actions":["view","export"]},{"segment":"results","actions":["view","export"]},{"segment":"genetic","actions":["view","export"]},{"segment":"statements","actions":["view"]}]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true),
  ('northwind-synthetic', 'employer-sponsor-admin', 1, '[]'::jsonb, 'active', 'synthetic-it-admin-001', 'initial-minimum-necessary-baseline', true)
ON CONFLICT (tenant_id, role_key, version) DO UPDATE
SET permits = EXCLUDED.permits,
    status = EXCLUDED.status,
    changed_by = EXCLUDED.changed_by,
    change_reason = EXCLUDED.change_reason,
    synthetic = EXCLUDED.synthetic;
-- pdp:generated:end

-- One active staff assignment: the template reference IS the permit set.
INSERT INTO identity.role_assignment
  (tenant_id, assignment_id, staff_account_id, staff_person_id, role_key,
   template_version, location_scope, effective_date, status, ended_reason,
   ended_by, assigned_by, synthetic)
VALUES
  ('northwind-synthetic', 'nra-morgan-itsec', 'nsa-morgan-lee', 'np-morgan-lee',
   'it-security-admin', 1, '{}', '2026-01-05', 'active', NULL, NULL,
   'synthetic-it-admin-001', true)
ON CONFLICT (tenant_id, assignment_id) DO UPDATE
SET staff_account_id = EXCLUDED.staff_account_id,
    staff_person_id = EXCLUDED.staff_person_id,
    role_key = EXCLUDED.role_key,
    template_version = EXCLUDED.template_version,
    location_scope = EXCLUDED.location_scope,
    effective_date = EXCLUDED.effective_date,
    status = EXCLUDED.status,
    ended_reason = EXCLUDED.ended_reason,
    ended_by = EXCLUDED.ended_by,
    assigned_by = EXCLUDED.assigned_by,
    synthetic = EXCLUDED.synthetic;

-- One justified, approved, time-boxed, review-flagged override.
INSERT INTO identity.access_override
  (tenant_id, override_id, staff_account_id, segment, actions, justification,
   approved_by, expires_on, flagged_for_review, status, synthetic)
VALUES
  ('northwind-synthetic', 'nov-morgan-docs', 'nsa-morgan-lee', 'documents', '{view}',
   'synthetic records-request intake coverage', 'synthetic-compliance-officer-001',
   '2026-09-30', true, 'active', true)
ON CONFLICT (tenant_id, override_id) DO UPDATE
SET staff_account_id = EXCLUDED.staff_account_id,
    segment = EXCLUDED.segment,
    actions = EXCLUDED.actions,
    justification = EXCLUDED.justification,
    approved_by = EXCLUDED.approved_by,
    expires_on = EXCLUDED.expires_on,
    flagged_for_review = EXCLUDED.flagged_for_review,
    status = EXCLUDED.status,
    synthetic = EXCLUDED.synthetic;

-- Guardian-minor authority over the seeded household minor (Alex ->
-- Casey), scoped, evidenced, verified; Riverbend carries a PENDING record —
-- unverified authority never grants (REQ-ID-006 EX-1).
INSERT INTO identity.authority_record
  (tenant_id, authority_id, version, kind, grantee_person_id, subject_person_id,
   scope, jurisdiction, evidence_ref, triggering_evidence_ref, written_consent_ref,
   consent_captured_on, confidential_access_basis_ref, effective_date, expires_on,
   renewal_owner_ref, verified_by, status, supersedes_version, ended_reason,
   decided_by, synthetic)
VALUES
  ('northwind-synthetic', 'nar-alex-casey', 1, 'guardian-minor', 'np-alex-rivera',
   'np-casey-rivera',
   '[{"segment":"scheduling","actions":["view","edit"]},{"segment":"messaging","actions":["view","edit"]},{"segment":"results","actions":["view"]}]'::jsonb,
   'NV', 'synthetic-guardian-evidence-0001', NULL, 'synthetic-written-consent-0001',
   '2026-01-10', NULL, '2026-01-10', NULL, NULL, 'synthetic-front-desk-001', 'active',
   NULL, NULL, 'synthetic-front-desk-001', true),
  ('riverbend-synthetic', 'rar-taylor-drew', 1, 'guardian-minor', 'rb-taylor-quinn',
   'rb-drew-quinn',
   '[{"segment":"scheduling","actions":["view"]}]'::jsonb,
   NULL, 'synthetic-authority-evidence-0101', NULL, NULL, NULL, NULL, '2026-02-01',
   NULL, NULL, NULL, 'pending-verification', NULL, NULL,
   'synthetic-front-desk-101', true)
ON CONFLICT (tenant_id, authority_id, version) DO UPDATE
SET kind = EXCLUDED.kind,
    grantee_person_id = EXCLUDED.grantee_person_id,
    subject_person_id = EXCLUDED.subject_person_id,
    scope = EXCLUDED.scope,
    jurisdiction = EXCLUDED.jurisdiction,
    evidence_ref = EXCLUDED.evidence_ref,
    triggering_evidence_ref = EXCLUDED.triggering_evidence_ref,
    written_consent_ref = EXCLUDED.written_consent_ref,
    consent_captured_on = EXCLUDED.consent_captured_on,
    confidential_access_basis_ref = EXCLUDED.confidential_access_basis_ref,
    effective_date = EXCLUDED.effective_date,
    expires_on = EXCLUDED.expires_on,
    renewal_owner_ref = EXCLUDED.renewal_owner_ref,
    verified_by = EXCLUDED.verified_by,
    status = EXCLUDED.status,
    supersedes_version = EXCLUDED.supersedes_version,
    ended_reason = EXCLUDED.ended_reason,
    decided_by = EXCLUDED.decided_by,
    synthetic = EXCLUDED.synthetic;

-- Deceased flag: append-only history — never rewritten by a re-seed.
INSERT INTO identity.person_flag
  (tenant_id, flag_id, person_id, kind, action, source_ref,
   correction_evidence_ref, actor_ref, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'nfl-0001', 'np-riley-fox', 'deceased', 'set',
   'synthetic-death-report-0001', NULL, 'synthetic-front-desk-001',
   '2026-03-18T09:30:00Z', true)
ON CONFLICT (tenant_id, flag_id) DO NOTHING;

-- Partition registry: a confirmed genetic tag per tenant, plus the
-- migrated-unclassifiable quarantine row (blocked from release BY CHECK).
INSERT INTO identity.partition_tag
  (tenant_id, tag_id, subject_person_id, artifact_ref, tag, ingest_path,
   review_status, blocked_from_release, synthetic)
VALUES
  ('northwind-synthetic', 'npt-0001', 'np-alex-rivera', 'synthetic-lab-result:lr-9001',
   'gipa-genetic', 'lab-interface', 'auto-confirmed', false, true),
  ('northwind-synthetic', 'npt-0002', 'np-sam-porter', 'legacy-lakeside:doc-771',
   'gipa-genetic', 'migration-workbench', 'needs-classification-review', true, true),
  ('riverbend-synthetic', 'rpt-0101', 'rb-taylor-quinn', 'synthetic-lab-result:lr-8101',
   'gipa-genetic', 'lab-interface', 'auto-confirmed', false, true)
ON CONFLICT (tenant_id, tag_id) DO UPDATE
SET subject_person_id = EXCLUDED.subject_person_id,
    artifact_ref = EXCLUDED.artifact_ref,
    tag = EXCLUDED.tag,
    ingest_path = EXCLUDED.ingest_path,
    review_status = EXCLUDED.review_status,
    blocked_from_release = EXCLUDED.blocked_from_release,
    synthetic = EXCLUDED.synthetic;

-- GIPA authorizations: one live, one date-expired — the send-time recheck
-- standing pair (an export against nga-0002 must exclude genetic today).
INSERT INTO identity.gipa_authorization
  (tenant_id, authorization_id, subject_person_id, scope_ref, granted_on,
   expires_on, written_evidence_ref, status, synthetic)
VALUES
  ('northwind-synthetic', 'nga-0001', 'np-alex-rivera',
   'synthetic-gipa-scope-life-insurer', '2026-02-01', '2027-02-01',
   'synthetic-gipa-written-0001', 'active', true),
  ('northwind-synthetic', 'nga-0002', 'np-sam-porter',
   'synthetic-gipa-scope-prior-provider', '2025-01-15', '2026-01-15',
   'synthetic-gipa-written-0002', 'active', true)
ON CONFLICT (tenant_id, authorization_id) DO UPDATE
SET subject_person_id = EXCLUDED.subject_person_id,
    scope_ref = EXCLUDED.scope_ref,
    granted_on = EXCLUDED.granted_on,
    expires_on = EXCLUDED.expires_on,
    written_evidence_ref = EXCLUDED.written_evidence_ref,
    status = EXCLUDED.status,
    synthetic = EXCLUDED.synthetic;
