-- WP-018 synthetic consent seed. Applied by `pnpm local:seed` after module
-- migrations (tables come from modules/consent/migrations/0009-consent.sql).
-- Idempotent: events insert with ON CONFLICT DO NOTHING (the log is
-- append-only; re-seeding never rewrites history); the projection upserts to
-- the fold of the event log. Synthetic data only. Standing proofs:
--   * sms/treatment opted_in (canSend allow) beside sms/marketing revoked by
--     a STOP keyword (opted_out — R6-REQ-072 / REQ-COMM-005);
--   * a live MHRA records-disclosure consent (granted) beside a lapsed one
--     (expired as-of — R6-SR-041);
--   * a voice/treatment opt-in with NO ai_voice event (ai_voice fails closed
--     on the distinct channel — R6-REQ-074);
--   * a genetic disclosure with written authorization (R6-SR-031);
--   * a compliance-blocked email/marketing consent; and a Riverbend
--     opted-out sms/marketing consent for the cross-tenant negatives.
--
-- The section between the consent markers is emitted by
-- renderConsentSeedSection(syntheticConsentSeedV1); the drift test and the DB
-- projection-sync test fail on divergence.

-- consent:generated:begin
-- Generated by @practicehub/consent renderConsentSeedSection from
-- syntheticConsentSeedV1. Regenerate on any seed change; the drift test and
-- the DB projection-sync test fail on divergence.
INSERT INTO consent.consent_event
  (tenant_id, consent_event_id, person_ref, scope_type, scope_key, channel,
   purpose, recipient_ref, record_type, action, resulting_state, effective_at,
   expires_at, source, evidence_ref, evidence_hash, captured_by, jurisdiction,
   policy_version, quiet_hours_tz, partition_tags, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'nce-0001', 'np-sam-porter', 'communication', 'communication|channel=sms|purpose=treatment', 'sms', 'treatment', NULL, NULL, 'grant', 'opted_in', '2026-02-01T00:00:00Z', NULL, 'portal_form', 'synthetic-consent:nce-0001-portal', '88fd66a192a9a0029bb6be4dcaf5f501bab5a2945389cdc5c070d6f77008ebf3', NULL, 'NV', 'consent-v1', 'America/Los_Angeles', '{}'::text[], '2026-02-01T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0002', 'np-sam-porter', 'communication', 'communication|channel=sms|purpose=marketing', 'sms', 'marketing', NULL, NULL, 'grant', 'opted_in', '2026-02-01T00:00:00Z', NULL, 'double_optin', 'synthetic-consent:nce-0002-double-optin', 'e4a6bafc9890d8f082c484a7a42bd76653454cfe7cdef363df67f1d54341e1ed', NULL, 'NV', 'consent-v1', 'America/Los_Angeles', '{}'::text[], '2026-02-01T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0003', 'np-sam-porter', 'communication', 'communication|channel=sms|purpose=marketing', 'sms', 'marketing', NULL, NULL, 'revoke', 'opted_out', '2026-03-01T00:00:00Z', NULL, 'sms_keyword', 'synthetic-inbound:nce-0003-stop', NULL, NULL, 'NV', 'consent-v1', 'America/Los_Angeles', '{}'::text[], '2026-03-01T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0004', 'np-riley-quinn', 'disclosure', 'disclosure|purpose=treatment|recipient=synthetic-recipient:referral-partner-0007|record=general', NULL, 'treatment', 'synthetic-recipient:referral-partner-0007', 'general', 'grant', 'opted_in', '2026-01-15T00:00:00Z', '2027-01-15T00:00:00Z', 'paper_form', 'synthetic-consent:nce-0004-mhra-release', '5fa2e8ad068051795efb77a70a3a4e20bfbe93e53691f20fcbdda88d648b30d3', NULL, 'MN', 'records-consent-v1', 'UTC', '{}'::text[], '2026-01-15T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0005', 'np-riley-quinn', 'disclosure', 'disclosure|purpose=treatment|recipient=synthetic-recipient:referral-partner-0008|record=general', NULL, 'treatment', 'synthetic-recipient:referral-partner-0008', 'general', 'grant', 'opted_in', '2024-01-15T00:00:00Z', '2025-01-15T00:00:00Z', 'paper_form', 'synthetic-consent:nce-0005-mhra-release', '477bd623705641ca36d4f5ab5c4574325db1d7fc6cd816af60ca7212ef03af1b', NULL, 'MN', 'records-consent-v1', 'UTC', '{}'::text[], '2024-01-15T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0006', 'np-jordan-kim', 'communication', 'communication|channel=voice|purpose=treatment', 'voice', 'treatment', NULL, NULL, 'grant', 'opted_in', '2026-02-10T00:00:00Z', NULL, 'staff_entry', 'synthetic-consent:nce-0006-verbal', NULL, NULL, 'IL', 'consent-v1', 'UTC', '{}'::text[], '2026-02-10T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0007', 'np-jordan-kim', 'disclosure', 'disclosure|purpose=treatment|recipient=synthetic-recipient:lab-0003|record=genetic', NULL, 'treatment', 'synthetic-recipient:lab-0003', 'genetic', 'grant', 'opted_in', '2026-02-10T00:00:00Z', NULL, 'paper_form', 'synthetic-consent:nce-0007-genetic-authorization', '774a6057fcde74595abc49d0862f9aec595cc4f665168581bef2d1ef3e188a64', NULL, 'IL', 'genetic-authorization-v1', 'UTC', ARRAY['gipa-genetic']::text[], '2026-02-10T00:00:00Z', true),
  ('northwind-synthetic', 'nce-0008', 'np-alex-rivera', 'communication', 'communication|channel=email|purpose=marketing', 'email', 'marketing', NULL, NULL, 'block', 'blocked', '2026-03-05T00:00:00Z', NULL, 'staff_entry', 'synthetic-compliance-hold:nce-0008', NULL, NULL, 'NV', 'consent-v1', 'UTC', '{}'::text[], '2026-03-05T00:00:00Z', true),
  ('riverbend-synthetic', 'rce-0001', 'rb-taylor-quinn', 'communication', 'communication|channel=sms|purpose=marketing', 'sms', 'marketing', NULL, NULL, 'grant', 'opted_in', '2026-02-01T00:00:00Z', NULL, 'double_optin', 'synthetic-consent:rce-0001-double-optin', 'f165d6d6288772de0d2c25d1a37345893300f9c5efa40168dbf0d312762d43f5', NULL, 'NV', 'consent-v1', 'UTC', '{}'::text[], '2026-02-01T00:00:00Z', true),
  ('riverbend-synthetic', 'rce-0002', 'rb-taylor-quinn', 'communication', 'communication|channel=sms|purpose=marketing', 'sms', 'marketing', NULL, NULL, 'revoke', 'opted_out', '2026-03-01T00:00:00Z', NULL, 'sms_keyword', 'synthetic-inbound:rce-0002-stop', NULL, NULL, 'NV', 'consent-v1', 'UTC', '{}'::text[], '2026-03-01T00:00:00Z', true)
ON CONFLICT (tenant_id, consent_event_id) DO NOTHING;

INSERT INTO consent.consent_state
  (tenant_id, person_ref, scope_key, scope_type, channel, purpose,
   recipient_ref, record_type, current_state, effective_at, expires_at,
   last_event_id, quiet_hours_tz, jurisdiction, synthetic)
VALUES
  ('northwind-synthetic', 'np-alex-rivera', 'communication|channel=email|purpose=marketing', 'communication', 'email', 'marketing', NULL, NULL, 'blocked', '2026-03-05T00:00:00Z', NULL, 'nce-0008', 'UTC', 'NV', true),
  ('northwind-synthetic', 'np-jordan-kim', 'communication|channel=voice|purpose=treatment', 'communication', 'voice', 'treatment', NULL, NULL, 'opted_in', '2026-02-10T00:00:00Z', NULL, 'nce-0006', 'UTC', 'IL', true),
  ('northwind-synthetic', 'np-jordan-kim', 'disclosure|purpose=treatment|recipient=synthetic-recipient:lab-0003|record=genetic', 'disclosure', NULL, 'treatment', 'synthetic-recipient:lab-0003', 'genetic', 'opted_in', '2026-02-10T00:00:00Z', NULL, 'nce-0007', 'UTC', 'IL', true),
  ('northwind-synthetic', 'np-riley-quinn', 'disclosure|purpose=treatment|recipient=synthetic-recipient:referral-partner-0007|record=general', 'disclosure', NULL, 'treatment', 'synthetic-recipient:referral-partner-0007', 'general', 'opted_in', '2026-01-15T00:00:00Z', '2027-01-15T00:00:00Z', 'nce-0004', 'UTC', 'MN', true),
  ('northwind-synthetic', 'np-riley-quinn', 'disclosure|purpose=treatment|recipient=synthetic-recipient:referral-partner-0008|record=general', 'disclosure', NULL, 'treatment', 'synthetic-recipient:referral-partner-0008', 'general', 'opted_in', '2024-01-15T00:00:00Z', '2025-01-15T00:00:00Z', 'nce-0005', 'UTC', 'MN', true),
  ('northwind-synthetic', 'np-sam-porter', 'communication|channel=sms|purpose=marketing', 'communication', 'sms', 'marketing', NULL, NULL, 'opted_out', '2026-03-01T00:00:00Z', NULL, 'nce-0003', 'America/Los_Angeles', 'NV', true),
  ('northwind-synthetic', 'np-sam-porter', 'communication|channel=sms|purpose=treatment', 'communication', 'sms', 'treatment', NULL, NULL, 'opted_in', '2026-02-01T00:00:00Z', NULL, 'nce-0001', 'America/Los_Angeles', 'NV', true),
  ('riverbend-synthetic', 'rb-taylor-quinn', 'communication|channel=sms|purpose=marketing', 'communication', 'sms', 'marketing', NULL, NULL, 'opted_out', '2026-03-01T00:00:00Z', NULL, 'rce-0002', 'UTC', 'NV', true)
ON CONFLICT (tenant_id, person_ref, scope_key) DO UPDATE
SET scope_type = EXCLUDED.scope_type,
    channel = EXCLUDED.channel,
    purpose = EXCLUDED.purpose,
    recipient_ref = EXCLUDED.recipient_ref,
    record_type = EXCLUDED.record_type,
    current_state = EXCLUDED.current_state,
    effective_at = EXCLUDED.effective_at,
    expires_at = EXCLUDED.expires_at,
    last_event_id = EXCLUDED.last_event_id,
    quiet_hours_tz = EXCLUDED.quiet_hours_tz,
    jurisdiction = EXCLUDED.jurisdiction,
    synthetic = EXCLUDED.synthetic;
-- consent:generated:end
