-- WP-021 events spine seed: synthetic outbox envelopes, the delivery
-- projection the drainer advances, and the per-consumer inbox dedup rows.
-- Generated from modules/events/src/seed-data.ts (syntheticEventsSeedV1) via
-- renderEventsSeedSection; a drift test and the DB suite fail on divergence.
-- Regenerate only through a byte-faithful writer (WP-020 lesson).
-- Depends on 0010-events.sql + 003-tenancy-seed.sql (tenant rows).

-- events:generated:begin
-- Generated by @practicehub/events renderEventsSeedSection from
-- syntheticEventsSeedV1. Regenerate on any seed change; the drift test and
-- the DB suite fail on divergence.
INSERT INTO events.outbox
  (tenant_id, event_id, legal_entity_id, type, aggregate_type, aggregate_id,
   aggregate_version, occurred_at, recorded_at, effective_at, source_module,
   source_actor_ref, correlation_id, causation_id, idempotency_key,
   data_classification, retention_class, supersedes_event_id, reversal_of_event_id,
   external_receipt_ref, payload, synthetic)
VALUES
  ('northwind-synthetic', '01KJKB3Q003AHRZ6DMV29GQY5C', NULL, 'consent.recorded', 'consent-ledger', 'np-sam-porter', 1, '2026-03-01T00:00:00Z', '2026-03-01T00:00:00Z', NULL, 'consent', 'synthetic-staff:intake', NULL, NULL, 'consent:np-sam-porter:recorded:0001', 'demographic', 'consent-artifact', NULL, NULL, NULL, '{"scope":"sms/treatment","state":"opted_in"}'::jsonb, true),
  ('northwind-synthetic', '01KJKB3QZ83AHRZ6DMV29GQY5C', NULL, 'thread.message-received', 'thread', 'th-0001', 2, '2026-03-02T00:00:00Z', '2026-03-02T00:00:00Z', NULL, 'comms', NULL, NULL, NULL, 'thread:th-0001:message:0002', 'PHI', NULL, NULL, NULL, NULL, '{"channel":"sms","direction":"inbound"}'::jsonb, true),
  ('northwind-synthetic', '01KJKB3RYG3AHRZ6DMV29GQY5C', NULL, 'notification.dispatched', 'notification', 'ntf-0001', 1, '2026-03-03T00:00:00Z', '2026-03-03T00:00:00Z', NULL, 'comms', 'synthetic-system:dispatcher', 'saga:onboarding:0001', NULL, 'notification:ntf-0001:dispatch:0001', 'demographic', NULL, NULL, NULL, 'synthetic-receipt:cpaas-sim-0001', '{"channel":"sms","template":"welcome"}'::jsonb, true),
  ('riverbend-synthetic', '01KJKB3SXR3AHRZ6DMV29GQY5C', NULL, 'consent.revoked', 'consent-ledger', 'rb-taylor-quinn', 2, '2026-03-01T00:00:00Z', '2026-03-01T00:00:00Z', NULL, 'consent', NULL, NULL, NULL, 'consent:rb-taylor-quinn:revoked:0001', 'demographic', NULL, NULL, NULL, NULL, '{"scope":"sms/marketing","state":"opted_out"}'::jsonb, true)
ON CONFLICT (tenant_id, event_id) DO NOTHING;

INSERT INTO events.outbox_delivery
  (tenant_id, event_id, status, attempts, next_attempt_at, published_at, synthetic)
VALUES
  ('northwind-synthetic', '01KJKB3Q003AHRZ6DMV29GQY5C', 'published', 1, '2026-03-01T00:00:00Z', '2026-03-01T00:00:05Z', true),
  ('northwind-synthetic', '01KJKB3QZ83AHRZ6DMV29GQY5C', 'pending', 0, '2026-03-02T00:00:00Z', NULL, true),
  ('northwind-synthetic', '01KJKB3RYG3AHRZ6DMV29GQY5C', 'published', 1, '2026-03-03T00:00:00Z', '2026-03-03T00:00:02Z', true),
  ('riverbend-synthetic', '01KJKB3SXR3AHRZ6DMV29GQY5C', 'pending', 0, '2026-03-01T00:00:00Z', NULL, true)
ON CONFLICT (tenant_id, event_id) DO UPDATE
SET status = EXCLUDED.status,
    attempts = EXCLUDED.attempts,
    next_attempt_at = EXCLUDED.next_attempt_at,
    published_at = EXCLUDED.published_at,
    synthetic = EXCLUDED.synthetic;

INSERT INTO events.inbox
  (tenant_id, consumer, event_id, processed_at, outcome, synthetic)
VALUES
  ('northwind-synthetic', 'thread-projector', '01KJKB3Q003AHRZ6DMV29GQY5C', '2026-03-01T00:00:05Z', 'processed', true),
  ('northwind-synthetic', 'audit-mirror', '01KJKB3RYG3AHRZ6DMV29GQY5C', '2026-03-03T00:00:02Z', 'processed', true)
ON CONFLICT (tenant_id, consumer, event_id) DO NOTHING;
-- events:generated:end
