-- WP-019 policy/disclosure registry + obligation-clock engine synthetic seed
-- (M03). GENERATED from @practicehub/consent syntheticPolicyClockSeedV1 via
-- renderPolicyClockSeedSection; a drift test compares this file against a
-- fresh emission and the DB suite re-folds the clock event log against the
-- seeded projection. Applied by tools/local-tools after 012-events-seed.sql.

-- policy-clocks:generated:begin
-- Generated by @practicehub/consent renderPolicyClockSeedSection from
-- syntheticPolicyClockSeedV1. Regenerate on any seed change; the drift test
-- and the DB projection-sync test fail on divergence.
INSERT INTO consent.obligation_clock_policy
  (obligation_type, jurisdiction, version, effective_on, status,
   counsel_signoff_ref, change_control_ref, duration_days, escalation_lead_days,
   source_ref, synthetic)
VALUES
  ('breach-notification', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-breach-floor-v1', 60, 20, 'hipaa-45-cfr-164-404-federal-breach-floor', true),
  ('breach-notification', 'FL', 1, DATE '2026-01-01', 'draft', NULL, 'wp-019-breach-fl-v1', 30, 10, 'fl-stat-501-171-breach-shorter-clock', true),
  ('mhra-renewal', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-mhra-floor-v1', NULL, 30, 'mn-stat-144-293-mhra-release-expiry', true),
  ('records-request-closure', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-access-floor-v1', 30, 10, 'hipaa-45-cfr-164-524-right-of-access', true),
  ('rule-pack-review', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-tracker-floor-v1', 90, 14, 'r6-sr-102-quarterly-statute-tracker', true)
-- Append-only reference registry: a version is immutable, never rewritten.
ON CONFLICT (obligation_type, jurisdiction, version) DO NOTHING;

INSERT INTO consent.policy_document
  (tenant_id, document_type, jurisdiction, version, effective_on, status,
   counsel_signoff_ref, change_control_ref, content_ref, content_hash, synthetic)
VALUES
  ('northwind-synthetic', 'disclosure-authorization', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-disclosure-floor-v1', 'policy-doc:northwind:disclosure-authorization:floor:v1', '4909fbe340ba24026e46a0cc7145aa0627bab4e00a3613e2078537d13b6ec623', true),
  ('northwind-synthetic', 'disclosure-authorization', 'MN', 1, DATE '2026-01-01', 'draft', NULL, 'wp-019-disclosure-mn-v1', 'policy-doc:northwind:disclosure-authorization:mn:v1', '0dede8ebecc52f163a4071ef1ad5857c97a75a6331fa45f22e9f71b84cee0c5e', true),
  ('northwind-synthetic', 'ai-disclosure', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-ai-disclosure-floor-v1', 'policy-doc:northwind:ai-disclosure:floor:v1', 'ce1be2c1ce0bbcb46abf8aeb6224d964d8df6a1a3fa002063e6a00ce2e647313', true),
  ('riverbend-synthetic', 'disclosure-authorization', 'floor', 1, DATE '1970-01-01', 'draft', NULL, 'wp-019-rb-disclosure-floor-v1', 'policy-doc:riverbend:disclosure-authorization:floor:v1', 'ad1b82f89ee72bced48ef0e7cc821709164632939f0d4d02c8385cde314e59fa', true)
-- Append-only: a policy document version is immutable; new documents are
-- new versions, never rewrites.
ON CONFLICT (tenant_id, document_type, jurisdiction, version) DO NOTHING;

INSERT INTO consent.obligation_clock_event
  (tenant_id, clock_event_id, clock_id, obligation_type, kind, subject_ref,
   occurred_at, due_at, evidence_ref, evidence_hash, actor_ref, reason,
   trigger_ref, escalate_at, owner_role, governing_policy_ref,
   change_control_ref, truth_table_receipt_ref, synthetic)
VALUES
  ('northwind-synthetic', 'ncle-0001', 'ncl-mhra-0001', 'mhra-renewal', 'trigger', 'np-riley-quinn', '2026-01-15T00:00:00.000Z', '2027-01-15T00:00:00.000Z', NULL, NULL, 'synthetic-platform-clock', NULL, 'consent:nce-0004', '2026-12-16T00:00:00.000Z', 'compliance', 'mhra-renewal:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0002', 'ncl-access-0001', 'records-request-closure', 'trigger', 'np-jordan-kim', '2026-02-10T00:00:00.000Z', '2026-03-12T00:00:00.000Z', NULL, NULL, 'synthetic-platform-clock', NULL, 'records-request:synthetic-req-0001', '2026-03-02T00:00:00.000Z', 'compliance', 'records-request-closure:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0003', 'ncl-access-0001', 'records-request-closure', 'satisfy', 'np-jordan-kim', '2026-02-20T00:00:00.000Z', NULL, 'records-release:synthetic-req-0001', 'b5b2c11fd7627a87457075e9f5122ee83ee683af20304543cd905f1c304df865', 'synthetic-records-officer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0004', 'ncl-tracker-0001', 'rule-pack-review', 'trigger', 'rule-pack-scope:all-jurisdictions', '2026-01-01T00:00:00.000Z', '2026-04-01T00:00:00.000Z', NULL, NULL, 'synthetic-platform-clock', NULL, 'statute-tracker:synthetic-cycle-0001', '2026-03-18T00:00:00.000Z', 'compliance', 'rule-pack-review:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0005', 'ncl-tracker-0001', 'rule-pack-review', 'escalate', 'rule-pack-scope:all-jurisdictions', '2026-03-18T00:00:00.000Z', NULL, NULL, NULL, 'synthetic-platform-clock', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0006', 'ncl-breach-0001', 'breach-notification', 'trigger', 'incident:synthetic-breach-0001', '2026-03-01T00:00:00.000Z', '2026-03-31T00:00:00.000Z', NULL, NULL, 'synthetic-compliance-officer', NULL, 'incident:synthetic-breach-0001', '2026-03-21T00:00:00.000Z', 'compliance', 'breach-notification:fl:v1', NULL, NULL, true),
  ('riverbend-synthetic', 'rcle-0001', 'rcl-breach-0001', 'breach-notification', 'trigger', 'incident:synthetic-rb-breach-0001', '2026-03-01T00:00:00.000Z', '2026-04-30T00:00:00.000Z', NULL, NULL, 'synthetic-compliance-officer', NULL, 'incident:synthetic-rb-breach-0001', '2026-04-10T00:00:00.000Z', 'compliance', 'breach-notification:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0007', 'ncl-access-0002', 'records-request-closure', 'trigger', 'np-alex-lee', '2026-02-15T00:00:00.000Z', '2026-03-17T00:00:00.000Z', NULL, NULL, 'synthetic-platform-clock', NULL, 'records-request:synthetic-req-0002', '2026-03-07T00:00:00.000Z', 'compliance', 'records-request-closure:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0008', 'ncl-access-0002', 'records-request-closure', 'cancel', 'np-alex-lee', '2026-02-18T00:00:00.000Z', NULL, NULL, NULL, 'synthetic-records-officer', 'records request withdrawn by the requester', NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0009', 'ncl-mhra-0002', 'mhra-renewal', 'trigger', 'np-morgan-reed', '2025-01-10T00:00:00.000Z', '2026-01-10T00:00:00.000Z', NULL, NULL, 'synthetic-platform-clock', NULL, 'consent:nce-synthetic-mhra-0002', '2025-12-11T00:00:00.000Z', 'compliance', 'mhra-renewal:floor:v1', NULL, NULL, true),
  ('northwind-synthetic', 'ncle-0010', 'ncl-mhra-0002', 'mhra-renewal', 'expire-fired', 'np-morgan-reed', '2026-01-10T00:00:00.000Z', NULL, NULL, NULL, 'synthetic-platform-clock', 'renewal window lapsed — consent auto-expired (R6-SR-041)', NULL, NULL, NULL, NULL, NULL, NULL, true)
ON CONFLICT (tenant_id, clock_event_id) DO NOTHING;

INSERT INTO consent.obligation_clock
  (tenant_id, clock_id, obligation_type, subject_ref, trigger_ref, triggered_at,
   due_at, escalate_at, status, owner_role, closure_evidence_ref, last_event_id,
   expire_fired, synthetic)
VALUES
  ('northwind-synthetic', 'ncl-access-0001', 'records-request-closure', 'np-jordan-kim', 'records-request:synthetic-req-0001', '2026-02-10T00:00:00.000Z', '2026-03-12T00:00:00.000Z', '2026-03-02T00:00:00.000Z', 'satisfied', 'compliance', 'records-release:synthetic-req-0001', 'ncle-0003', false, true),
  ('northwind-synthetic', 'ncl-access-0002', 'records-request-closure', 'np-alex-lee', 'records-request:synthetic-req-0002', '2026-02-15T00:00:00.000Z', '2026-03-17T00:00:00.000Z', '2026-03-07T00:00:00.000Z', 'cancelled', 'compliance', NULL, 'ncle-0008', false, true),
  ('northwind-synthetic', 'ncl-breach-0001', 'breach-notification', 'incident:synthetic-breach-0001', 'incident:synthetic-breach-0001', '2026-03-01T00:00:00.000Z', '2026-03-31T00:00:00.000Z', '2026-03-21T00:00:00.000Z', 'pending', 'compliance', NULL, 'ncle-0006', false, true),
  ('northwind-synthetic', 'ncl-mhra-0001', 'mhra-renewal', 'np-riley-quinn', 'consent:nce-0004', '2026-01-15T00:00:00.000Z', '2027-01-15T00:00:00.000Z', '2026-12-16T00:00:00.000Z', 'pending', 'compliance', NULL, 'ncle-0001', false, true),
  ('northwind-synthetic', 'ncl-mhra-0002', 'mhra-renewal', 'np-morgan-reed', 'consent:nce-synthetic-mhra-0002', '2025-01-10T00:00:00.000Z', '2026-01-10T00:00:00.000Z', '2025-12-11T00:00:00.000Z', 'pending', 'compliance', NULL, 'ncle-0010', true, true),
  ('northwind-synthetic', 'ncl-tracker-0001', 'rule-pack-review', 'rule-pack-scope:all-jurisdictions', 'statute-tracker:synthetic-cycle-0001', '2026-01-01T00:00:00.000Z', '2026-04-01T00:00:00.000Z', '2026-03-18T00:00:00.000Z', 'escalated', 'compliance', NULL, 'ncle-0005', false, true),
  ('riverbend-synthetic', 'rcl-breach-0001', 'breach-notification', 'incident:synthetic-rb-breach-0001', 'incident:synthetic-rb-breach-0001', '2026-03-01T00:00:00.000Z', '2026-04-30T00:00:00.000Z', '2026-04-10T00:00:00.000Z', 'pending', 'compliance', NULL, 'rcle-0001', false, true)
ON CONFLICT (tenant_id, clock_id) DO UPDATE
SET obligation_type = EXCLUDED.obligation_type,
    subject_ref = EXCLUDED.subject_ref,
    trigger_ref = EXCLUDED.trigger_ref,
    triggered_at = EXCLUDED.triggered_at,
    due_at = EXCLUDED.due_at,
    escalate_at = EXCLUDED.escalate_at,
    status = EXCLUDED.status,
    owner_role = EXCLUDED.owner_role,
    closure_evidence_ref = EXCLUDED.closure_evidence_ref,
    last_event_id = EXCLUDED.last_event_id,
    expire_fired = EXCLUDED.expire_fired,
    synthetic = EXCLUDED.synthetic;
-- policy-clocks:generated:end
