-- WP-022 workitems seed: the per-tier SLA policy registry plus synthetic
-- WorkItems with their append-only event logs and folded projections
-- (work_item + sla_timer). Generated from modules/events/src/sla-seed-data.ts
-- (syntheticWorkItemsSeedV1) via renderWorkItemsSeedSection; a drift test and
-- the DB suite fail on divergence. Regenerate only through a byte-faithful
-- writer (WP-020 lesson). Depends on 0012-workitems.sql + 003-tenancy-seed.sql.
-- workitems:generated:begin
-- Generated by @practicehub/events renderWorkItemsSeedSection from
-- syntheticWorkItemsSeedV1. Regenerate on any seed change; the drift test and
-- the DB suite fail on divergence.
INSERT INTO events.sla_policy
  (tenant_id, policy_id, version, effective_on, member_tier, hours_mode,
   first_response_target_minutes, next_response_target_minutes, resolution_target_minutes,
   escalation_chain, quiet_hours_exempt, change_control_ref, synthetic)
VALUES
  ('northwind-synthetic', 'sla-concierge', 1, '2026-01-01', 'concierge', 'after_hours', 60, 60, 240, '[{"afterMinutes":60,"action":"notify_owner","target":"synthetic-role:owner"},{"afterMinutes":60,"action":"notify_supervisor","target":"synthetic-supervisor:pod-a"},{"afterMinutes":300,"action":"notify_supervisor","target":"synthetic-supervisor:pod-a"},{"afterMinutes":300,"action":"mark_priority_high","target":"synthetic-escalation-queue:pod-a"}]'::jsonb, true, 'wp-022-sla-concierge-v1', true),
  ('northwind-synthetic', 'sla-employer', 1, '2026-01-01', 'employer-sponsored', 'business', 120, 120, 480, '[{"afterMinutes":120,"action":"notify_owner","target":"synthetic-role:owner"},{"afterMinutes":240,"action":"notify_supervisor","target":"synthetic-supervisor:pod-a"}]'::jsonb, false, 'wp-022-sla-employer-v1', true),
  ('northwind-synthetic', 'sla-non-member', 1, '2026-01-01', 'non-member', 'business', 240, 240, NULL, '[{"afterMinutes":240,"action":"notify_supervisor","target":"synthetic-supervisor:pod-b"}]'::jsonb, false, 'wp-022-sla-non-member-v1', true)
ON CONFLICT (tenant_id, policy_id, version) DO NOTHING;

INSERT INTO events.work_item
  (tenant_id, work_item_id, origin, subject_ref, purpose, risk, service_tier,
   sla_policy_id, policy_version, has_sla, status, priority, owner_ref, pool_id,
   watchers, escalated, opened_at, response_due_at, first_owned_at, last_event_seq, synthetic)
VALUES
  ('northwind-synthetic', 'wi-thread-william-0001', 'thread', 'thread:th-william-0001', 'member-message', 'routine', 'concierge', 'sla-concierge', 1, true, 'open', 'high', 'synthetic-guide:maya', NULL, '["synthetic-supervisor:pod-a","synthetic-guide:william"]'::jsonb, true, '2026-03-02T08:00:00Z', '2026-03-02T09:00:00Z', '2026-03-02T08:02:00Z', 15, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 'thread', 'thread:th-unmatched-0002', 'member-message', 'routine', 'concierge', 'sla-concierge', 1, true, 'unmatched', 'normal', NULL, 'synthetic-pool:front-desk', '[]'::jsonb, false, '2026-03-03T08:00:00Z', '2026-03-03T09:00:00Z', NULL, 4, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 'obligation-clock', 'clock:ncl-mhra-0001', 'consent-renewal', 'elevated', 'employer-sponsored', 'sla-employer', 1, true, 'open', 'normal', 'synthetic-guide:noor', NULL, '[]'::jsonb, false, '2026-03-04T08:00:00Z', '2026-03-04T10:00:00Z', '2026-03-04T08:30:00Z', 4, true),
  ('northwind-synthetic', 'wi-merge-review-0004', 'merge-review', 'merge-case:mc-0007', 'identity-harm-review', 'critical', 'concierge', 'sla-concierge', 1, true, 'unmatched', 'normal', NULL, 'synthetic-pool:identity-governance', '[]'::jsonb, false, '2026-03-05T08:00:00Z', '2026-03-05T09:00:00Z', NULL, 3, true),
  ('northwind-synthetic', 'wi-admin-0005', 'admin', NULL, 'inventory-count', 'routine', 'internal', NULL, NULL, false, 'open', 'normal', 'synthetic-guide:noor', NULL, '[]'::jsonb, false, '2026-03-01T08:00:00Z', NULL, '2026-03-01T08:00:00Z', 2, true),
  ('riverbend-synthetic', 'wi-thread-rb-0001', 'thread', 'thread:rb-th-0001', 'member-message', 'routine', 'non-member', NULL, NULL, false, 'unmatched', 'normal', NULL, 'synthetic-pool:rb-front-desk', '[]'::jsonb, false, '2026-03-02T08:00:00Z', NULL, NULL, 2, true)
ON CONFLICT (tenant_id, work_item_id) DO UPDATE
SET status = EXCLUDED.status, priority = EXCLUDED.priority, owner_ref = EXCLUDED.owner_ref,
    pool_id = EXCLUDED.pool_id, watchers = EXCLUDED.watchers, escalated = EXCLUDED.escalated,
    first_owned_at = EXCLUDED.first_owned_at, last_event_seq = EXCLUDED.last_event_seq;

INSERT INTO events.work_item_event
  (tenant_id, work_item_id, event_seq, event_type, occurred_at, actor_ref, from_owner_ref,
   to_owner_ref, reason, timer_type, due_at, escalation_step, escalation_action,
   escalation_target, context_package, watcher_ref, detail, synthetic)
VALUES
  ('northwind-synthetic', 'wi-thread-william-0001', 1, 'opened', '2026-03-02T08:00:00Z', 'synthetic-system:router', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 2, 'queued', '2026-03-02T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 3, 'inbound_received', '2026-03-02T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 4, 'timer_started', '2026-03-02T08:00:00Z', NULL, NULL, NULL, NULL, 'next_response', '2026-03-02T09:00:00Z', NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 5, 'assigned', '2026-03-02T08:02:00Z', 'synthetic-guide:william', NULL, 'synthetic-guide:william', 'assignment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 6, 'timer_breached', '2026-03-02T09:00:00Z', NULL, NULL, NULL, NULL, 'next_response', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 7, 'escalated', '2026-03-02T09:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'notify_owner', 'synthetic-guide:william', NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 8, 'watcher_added', '2026-03-02T09:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-supervisor:pod-a', '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 9, 'escalated', '2026-03-02T09:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, 1, 'notify_supervisor', 'synthetic-supervisor:pod-a', NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 10, 'escalated', '2026-03-02T13:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, 2, 'notify_supervisor', 'synthetic-supervisor:pod-a', NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 11, 'escalated', '2026-03-02T13:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, 3, 'mark_priority_high', 'synthetic-escalation-queue:pod-a', NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 12, 'holding_reply', '2026-03-02T13:10:00Z', 'synthetic-guide:maya', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 13, 'timer_paused', '2026-03-02T13:10:00Z', NULL, NULL, NULL, NULL, 'next_response', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 14, 'timer_started', '2026-03-02T13:10:00Z', NULL, NULL, NULL, NULL, 'resolution', '2026-03-02T17:10:00Z', NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 15, 'reassigned', '2026-03-02T13:15:00Z', 'synthetic-supervisor:pod-a', 'synthetic-guide:william', 'synthetic-guide:maya', 'escalation', NULL, NULL, NULL, NULL, NULL, '{"transcriptRef":"synthetic-transcript:th-william-0001","patientSummaryRef":"synthetic-summary:np-parker-vale","openOrders":["synthetic-order:vo2-panel"],"priorOwnerNotesRef":"synthetic-note:william-handoff-0001","timerState":[],"consentFlags":["sms/treatment:opted_in"]}'::jsonb, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 1, 'opened', '2026-03-03T08:00:00Z', 'synthetic-system:router', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 2, 'queued', '2026-03-03T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 3, 'inbound_received', '2026-03-03T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 4, 'timer_started', '2026-03-03T08:00:00Z', NULL, NULL, NULL, NULL, 'first_response', '2026-03-03T09:00:00Z', NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 1, 'opened', '2026-03-04T08:00:00Z', 'synthetic-system:clock-engine', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 2, 'queued', '2026-03-04T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 3, 'timer_started', '2026-03-04T08:00:00Z', NULL, NULL, NULL, NULL, 'first_response', '2026-03-04T10:00:00Z', NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 4, 'assigned', '2026-03-04T08:30:00Z', 'synthetic-guide:noor', NULL, 'synthetic-guide:noor', 'assignment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-merge-review-0004', 1, 'opened', '2026-03-05T08:00:00Z', 'synthetic-system:merge-governance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-merge-review-0004', 2, 'queued', '2026-03-05T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-merge-review-0004', 3, 'timer_started', '2026-03-05T08:00:00Z', NULL, NULL, NULL, NULL, 'first_response', '2026-03-05T09:00:00Z', NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-admin-0005', 1, 'opened', '2026-03-01T08:00:00Z', 'synthetic-guide:noor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('northwind-synthetic', 'wi-admin-0005', 2, 'assigned', '2026-03-01T08:00:00Z', 'synthetic-guide:noor', NULL, 'synthetic-guide:noor', 'assignment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('riverbend-synthetic', 'wi-thread-rb-0001', 1, 'opened', '2026-03-02T08:00:00Z', 'synthetic-system:router', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true),
  ('riverbend-synthetic', 'wi-thread-rb-0001', 2, 'queued', '2026-03-02T08:00:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, true)
ON CONFLICT (tenant_id, work_item_id, event_seq) DO NOTHING;

INSERT INTO events.sla_timer
  (tenant_id, work_item_id, timer_type, started_at, due_at, paused_total_seconds,
   state, last_event_seq, synthetic)
VALUES
  ('northwind-synthetic', 'wi-thread-william-0001', 'next_response', '2026-03-02T08:00:00Z', '2026-03-02T09:00:00Z', 0, 'paused', 15, true),
  ('northwind-synthetic', 'wi-thread-william-0001', 'resolution', '2026-03-02T13:10:00Z', '2026-03-02T17:10:00Z', 0, 'running', 15, true),
  ('northwind-synthetic', 'wi-thread-unmatched-0002', 'first_response', '2026-03-03T08:00:00Z', '2026-03-03T09:00:00Z', 0, 'running', 4, true),
  ('northwind-synthetic', 'wi-clock-mhra-0003', 'first_response', '2026-03-04T08:00:00Z', '2026-03-04T10:00:00Z', 0, 'running', 4, true),
  ('northwind-synthetic', 'wi-merge-review-0004', 'first_response', '2026-03-05T08:00:00Z', '2026-03-05T09:00:00Z', 0, 'running', 3, true)
ON CONFLICT (tenant_id, work_item_id, timer_type) DO UPDATE
SET started_at = EXCLUDED.started_at, due_at = EXCLUDED.due_at,
    paused_total_seconds = EXCLUDED.paused_total_seconds, state = EXCLUDED.state,
    last_event_seq = EXCLUDED.last_event_seq;
-- workitems:generated:end
