-- WP-023 on-call + coverage seed: the provisioned on-call rotation registry,
-- concrete schedule slots (rotation/override/vacated), a planned PTO coverage
-- window, open coverage-gap alerts, and coverage handoff artifacts. Generated
-- from modules/events/src/oncall-seed-data.ts (syntheticOnCallSeedV1) via
-- renderOnCallSeedSection; a drift test and the DB suite fail on divergence.
-- Regenerate only through a byte-faithful writer (WP-020 lesson). Depends on
-- 0014-oncall.sql + 003-tenancy-seed.sql.
-- oncall:generated:begin
-- Generated by @practicehub/events renderOnCallSeedSection from
-- syntheticOnCallSeedV1. Regenerate on any seed change; the drift test and
-- the DB suite fail on divergence.
INSERT INTO events.on_call_rotation
  (tenant_id, rotation_id, version, effective_on, location_id, coverage_mode,
   service_scopes, member_order, change_control_ref, synthetic)
VALUES
  ('northwind-synthetic', 'oncall-concierge-nv', 1, '2026-01-01', 'loc-nv-lasvegas', '24x7', '["concierge-urgent","longevity"]'::jsonb, '[{"memberRef":"synthetic-provider:reyes","serviceScopes":["concierge-urgent","longevity"]},{"memberRef":"synthetic-provider:okafor","serviceScopes":["concierge-urgent"]}]'::jsonb, 'wp-023-oncall-concierge-nv-v1', true),
  ('riverbend-synthetic', 'oncall-rb', 1, '2026-01-01', 'loc-rb-central', 'business', '["general"]'::jsonb, '[{"memberRef":"synthetic-provider:rb-lane","serviceScopes":["general"]}]'::jsonb, 'wp-023-oncall-rb-v1', true)
ON CONFLICT (tenant_id, rotation_id, version) DO NOTHING;

INSERT INTO events.on_call_slot
  (tenant_id, slot_id, rotation_id, kind, member_ref, service_scopes,
   window_start, window_end, status, synthetic)
VALUES
  ('northwind-synthetic', 'slot-nv-0001', 'oncall-concierge-nv', 'rotation', 'synthetic-provider:reyes', '["concierge-urgent","longevity"]'::jsonb, '2026-03-02T08:00:00Z', '2026-03-02T20:00:00Z', 'scheduled', true),
  ('northwind-synthetic', 'slot-nv-0002', 'oncall-concierge-nv', 'override', 'synthetic-provider:okafor', '["concierge-urgent"]'::jsonb, '2026-03-02T20:00:00Z', '2026-03-03T00:00:00Z', 'overridden', true),
  ('northwind-synthetic', 'slot-nv-0003', 'oncall-concierge-nv', 'rotation', 'synthetic-provider:departed', '["concierge-urgent","longevity"]'::jsonb, '2026-03-03T00:00:00Z', '2026-03-03T08:00:00Z', 'vacated', true),
  ('riverbend-synthetic', 'slot-rb-0001', 'oncall-rb', 'rotation', 'synthetic-provider:rb-lane', '["general"]'::jsonb, '2026-03-02T09:00:00Z', '2026-03-02T17:00:00Z', 'scheduled', true)
ON CONFLICT (tenant_id, slot_id) DO NOTHING;

INSERT INTO events.coverage_window
  (tenant_id, coverage_id, owner_ref, from_at, to_at, coverage_target_ref,
   target_kind, reason, status, synthetic)
VALUES
  ('northwind-synthetic', 'cov-noor-0001', 'synthetic-guide:noor', '2026-03-10T00:00:00Z', '2026-03-14T00:00:00Z', 'synthetic-guide:maya', 'owner', 'pto', 'planned', true)
ON CONFLICT (tenant_id, coverage_id) DO NOTHING;

INSERT INTO events.coverage_gap_alert
  (tenant_id, alert_id, rotation_id, location_id, service_scope, gap_start, gap_end,
   detected_reason, status, synthetic)
VALUES
  ('northwind-synthetic', 'gap-nv-0001', 'oncall-concierge-nv', 'loc-nv-lasvegas', 'concierge-urgent', '2026-03-03T00:00:00Z', '2026-03-03T08:00:00Z', 'vacated-slot', 'open', true),
  ('riverbend-synthetic', 'gap-rb-0001', 'oncall-rb', 'loc-rb-central', 'general', '2026-03-02T17:00:00Z', '2026-03-03T09:00:00Z', 'unfilled-window', 'open', true)
ON CONFLICT (tenant_id, alert_id) DO NOTHING;

INSERT INTO events.coverage_handoff
  (tenant_id, handoff_id, kind, from_owner_ref, to_owner_ref, generated_at,
   item_count, context_manifest, synthetic)
VALUES
  ('northwind-synthetic', 'handoff-noor-pto-0001', 'pto-coverage', 'synthetic-guide:noor', 'synthetic-guide:maya', '2026-03-09T18:00:00Z', 2, '[{"workItemId":"wi-thread-noor-0011","risk":"elevated","contextPackageRef":"synthetic-note:noor-handoff-0011"},{"workItemId":"wi-thread-noor-0012","risk":"routine","contextPackageRef":"synthetic-note:noor-handoff-0012"}]'::jsonb, true),
  ('northwind-synthetic', 'handoff-morning-0001', 'morning-handoff', 'synthetic-provider:okafor', 'synthetic-guide:noor', '2026-03-03T07:30:00Z', 1, '[{"workItemId":"wi-thread-overnight-0021","risk":"urgent","contextPackageRef":"synthetic-note:overnight-0021"}]'::jsonb, true)
ON CONFLICT (tenant_id, handoff_id) DO NOTHING;
-- oncall:generated:end
