-- WP-024 synthetic documents seed. Applied by `pnpm local:seed` after module
-- migrations (tables come from modules/documents/migrations/0015-documents.sql).
-- Idempotent: events insert with ON CONFLICT DO NOTHING (the log is
-- append-only; re-seeding never rewrites history); the projection upserts to
-- the fold of the event log. Synthetic data only. Standing proofs:
--   * a filed inbound fax matched to a chart (authority-bearing filing);
--   * a quarantined wrong-patient unsolicited record — reason + observed
--     attribute NAMES only, no PHI value (REQ-DOC-006);
--   * an unmatched portal upload still within its hold period (REQ-DOC-010);
--   * an unmatched inbound fax whose hold EXPIRED, disposed by return to
--     sender (REQ-DOC-011); and a Riverbend unmatched fax (cross-tenant).
--
-- The section between the documents markers is emitted by
-- renderDocumentsSeedSection(syntheticDocumentsSeedV1) in @practicehub/documents;
-- a drift test compares this file against a fresh emission, and the DB suite
-- folds the seeded events back against the seeded projection.
-- documents:generated:begin
-- Generated by @practicehub/documents renderDocumentsSeedSection from
-- syntheticDocumentsSeedV1. Regenerate on any seed change; the drift test and
-- the DB projection-sync test fail on divergence.
INSERT INTO documents.document_event
  (tenant_id, document_event_id, document_id, event_type, actor_ref, source,
   blob_ref, content_hash, content_bytes, media_type, page_count, partition_tags,
   hold_until, matched_person_ref, quarantine_reason, observed_attribute_names,
   disposition, redirect_target, evidence_ref, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'nde-0001', 'nd-0001', 'received', 'synthetic-fax-gateway', 'inbound_fax', 'blob://documents/47fa10c50c09e028ff41d1f3061e8901045d3a95d1ac3fbc52ebad0cd12e453f', '47fa10c50c09e028ff41d1f3061e8901045d3a95d1ac3fbc52ebad0cd12e453f', 49, 'application/pdf', 3, '{}'::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-01T09:00:00Z', true),
  ('northwind-synthetic', 'nde-0002', 'nd-0001', 'filed', 'synthetic-staff:records-clerk-001', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], NULL, 'np-sam-porter', NULL, NULL, NULL, NULL, 'synthetic-doc-evidence:nd-0001-verified-match', '2026-03-01T10:15:00Z', true),
  ('northwind-synthetic', 'nde-0003', 'nd-0002', 'received', 'synthetic-partner-gateway', 'partner_exchange', 'blob://documents/efce4b25ac17aec48acc5da1057dfa2c6cfe876204bbb6ee9e389ffb05de0681', 'efce4b25ac17aec48acc5da1057dfa2c6cfe876204bbb6ee9e389ffb05de0681', 61, 'application/pdf', 5, '{}'::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-02T14:00:00Z', true),
  ('northwind-synthetic', 'nde-0004', 'nd-0002', 'quarantined', 'synthetic-staff:records-clerk-001', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], NULL, NULL, 'wrong-patient', ARRAY['patient-name', 'date-of-birth', 'sender-fax']::text[], NULL, NULL, NULL, '2026-03-02T14:30:00Z', true),
  ('northwind-synthetic', 'nde-0005', 'nd-0003', 'received', 'synthetic-portal-intake', 'portal_upload', 'blob://documents/3912e5bcf064a5e4e97e11612d0a886a072371dfd30f5906cf8672303c6f5afd', '3912e5bcf064a5e4e97e11612d0a886a072371dfd30f5906cf8672303c6f5afd', 55, 'image/tiff', 1, '{}'::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-10T08:00:00Z', true),
  ('northwind-synthetic', 'nde-0006', 'nd-0003', 'auto_match_failed', 'synthetic-match-engine', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], '2026-04-09T08:05:00Z', NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-10T08:05:00Z', true),
  ('northwind-synthetic', 'nde-0007', 'nd-0004', 'received', 'synthetic-fax-gateway', 'inbound_fax', 'blob://documents/4705483e6cdca51a2807a8591360eb6351e44fd8b61928df6b27ab1b3ed2be53', '4705483e6cdca51a2807a8591360eb6351e44fd8b61928df6b27ab1b3ed2be53', 55, 'application/pdf', 2, '{}'::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-01-05T07:00:00Z', true),
  ('northwind-synthetic', 'nde-0008', 'nd-0004', 'auto_match_failed', 'synthetic-match-engine', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], '2026-02-04T07:05:00Z', NULL, NULL, NULL, NULL, NULL, NULL, '2026-01-05T07:05:00Z', true),
  ('northwind-synthetic', 'nde-0009', 'nd-0004', 'disposition_decided', 'synthetic-records-sweep', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], NULL, NULL, NULL, NULL, 'returned', NULL, 'synthetic-doc-evidence:nd-0004-return-to-sender', '2026-02-05T07:05:00Z', true),
  ('riverbend-synthetic', 'rde-0001', 'rd-0001', 'received', 'synthetic-fax-gateway', 'inbound_fax', 'blob://documents/6c1114c6d7acabf645dea7acf9ccfaf4d66bfde5231fba845c24323229d89578', '6c1114c6d7acabf645dea7acf9ccfaf4d66bfde5231fba845c24323229d89578', 52, 'application/pdf', 1, '{}'::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-04T11:00:00Z', true),
  ('riverbend-synthetic', 'rde-0002', 'rd-0001', 'auto_match_failed', 'synthetic-match-engine', NULL, NULL, NULL, NULL, NULL, NULL, '{}'::text[], '2026-04-03T11:05:00Z', NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-04T11:05:00Z', true)
ON CONFLICT (tenant_id, document_event_id) DO NOTHING;

INSERT INTO documents.document_state
  (tenant_id, document_id, status, source, blob_ref, content_hash, content_bytes,
   media_type, page_count, partition_tags, received_at, hold_until,
   matched_person_ref, quarantine_reason, observed_attribute_names, disposition,
   redirect_target, last_event_id, synthetic)
VALUES
  ('northwind-synthetic', 'nd-0001', 'filed', 'inbound_fax', 'blob://documents/47fa10c50c09e028ff41d1f3061e8901045d3a95d1ac3fbc52ebad0cd12e453f', '47fa10c50c09e028ff41d1f3061e8901045d3a95d1ac3fbc52ebad0cd12e453f', 49, 'application/pdf', 3, '{}'::text[], '2026-03-01T09:00:00Z', NULL, 'np-sam-porter', NULL, NULL, NULL, NULL, 'nde-0002', true),
  ('northwind-synthetic', 'nd-0002', 'quarantined', 'partner_exchange', 'blob://documents/efce4b25ac17aec48acc5da1057dfa2c6cfe876204bbb6ee9e389ffb05de0681', 'efce4b25ac17aec48acc5da1057dfa2c6cfe876204bbb6ee9e389ffb05de0681', 61, 'application/pdf', 5, '{}'::text[], '2026-03-02T14:00:00Z', NULL, NULL, 'wrong-patient', ARRAY['patient-name', 'date-of-birth', 'sender-fax']::text[], NULL, NULL, 'nde-0004', true),
  ('northwind-synthetic', 'nd-0003', 'unmatched', 'portal_upload', 'blob://documents/3912e5bcf064a5e4e97e11612d0a886a072371dfd30f5906cf8672303c6f5afd', '3912e5bcf064a5e4e97e11612d0a886a072371dfd30f5906cf8672303c6f5afd', 55, 'image/tiff', 1, '{}'::text[], '2026-03-10T08:00:00Z', '2026-04-09T08:05:00Z', NULL, NULL, NULL, NULL, NULL, 'nde-0006', true),
  ('northwind-synthetic', 'nd-0004', 'disposed', 'inbound_fax', 'blob://documents/4705483e6cdca51a2807a8591360eb6351e44fd8b61928df6b27ab1b3ed2be53', '4705483e6cdca51a2807a8591360eb6351e44fd8b61928df6b27ab1b3ed2be53', 55, 'application/pdf', 2, '{}'::text[], '2026-01-05T07:00:00Z', '2026-02-04T07:05:00Z', NULL, NULL, NULL, 'returned', NULL, 'nde-0009', true),
  ('riverbend-synthetic', 'rd-0001', 'unmatched', 'inbound_fax', 'blob://documents/6c1114c6d7acabf645dea7acf9ccfaf4d66bfde5231fba845c24323229d89578', '6c1114c6d7acabf645dea7acf9ccfaf4d66bfde5231fba845c24323229d89578', 52, 'application/pdf', 1, '{}'::text[], '2026-03-04T11:00:00Z', '2026-04-03T11:05:00Z', NULL, NULL, NULL, NULL, NULL, 'rde-0002', true)
ON CONFLICT (tenant_id, document_id) DO UPDATE
SET status = EXCLUDED.status,
    source = EXCLUDED.source,
    blob_ref = EXCLUDED.blob_ref,
    content_hash = EXCLUDED.content_hash,
    content_bytes = EXCLUDED.content_bytes,
    media_type = EXCLUDED.media_type,
    page_count = EXCLUDED.page_count,
    partition_tags = EXCLUDED.partition_tags,
    received_at = EXCLUDED.received_at,
    hold_until = EXCLUDED.hold_until,
    matched_person_ref = EXCLUDED.matched_person_ref,
    quarantine_reason = EXCLUDED.quarantine_reason,
    observed_attribute_names = EXCLUDED.observed_attribute_names,
    disposition = EXCLUDED.disposition,
    redirect_target = EXCLUDED.redirect_target,
    last_event_id = EXCLUDED.last_event_id,
    synthetic = EXCLUDED.synthetic;
-- documents:generated:end
