-- WP-025 synthetic documents-records seed. Applied by `pnpm local:seed` after
-- module migrations (tables come from
-- modules/documents/migrations/0016-documents-records.sql). Idempotent: append-only
-- logs insert with ON CONFLICT DO NOTHING; the search index and disclosure closure
-- upsert their mutable columns. Synthetic data only. Standing proofs:
--   * a version lineage with a superseding correction — the source is preserved
--     (REQ-DOC-003, HIPAA 164.526);
--   * a denied correction that lands the patient statement-of-disagreement while
--     the source stays current (REQ-DOC-003 exception);
--   * an e-sign executed version carrying a signature evidence chain (D5.4);
--   * a genetic-tagged search row a non-genetic-cleared search never surfaces
--     (REQ-DOC-013/016 partition-scoped-search negative);
--   * a completed records disclosure whose accounting excludes the genetic
--     artifact and is closed with delivery evidence (REQ-DOC-002/013/016); and a
--     Riverbend version + search row + still-transmitting disclosure (cross-tenant).
--
-- The section between the documents-records markers is emitted by
-- renderDocumentsRecordsSeedSection(syntheticDocumentsRecordsSeedV1) in
-- @practicehub/documents; a drift test compares this file against a fresh emission.
-- documents-records:generated:begin
-- Generated by @practicehub/documents renderDocumentsRecordsSeedSection from
-- syntheticDocumentsRecordsSeedV1. Regenerate on any seed change; the drift test
-- fails on divergence.
INSERT INTO documents.document_version
  (tenant_id, version_event_id, document_id, version_no, kind, blob_ref, content_hash,
   content_bytes, media_type, supersedes_version_no, concerns_version_no, reason_ref,
   esign_signer_refs, esign_method, esign_certificate_hash, esign_signed_at,
   esign_evidence_ref, actor_ref, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'ndv-0001', 'nd-0001', 1, 'original', 'blob://documents/66ef5daaa5c1fee60fb5af099bb9c10e508fdf29df7bb48007ffbf20e3ff5ac7', '66ef5daaa5c1fee60fb5af099bb9c10e508fdf29df7bb48007ffbf20e3ff5ac7', 52, 'application/pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-staff:records-clerk-001', '2026-03-01T10:20:00Z', true),
  ('northwind-synthetic', 'ndv-0002', 'nd-0001', 2, 'correction', 'blob://documents/688c67d0f2eb5fe5547c7833157fec21d8cdef9079287efe4e013015b2f2dba2', '688c67d0f2eb5fe5547c7833157fec21d8cdef9079287efe4e013015b2f2dba2', 62, 'application/pdf', 1, NULL, 'synthetic-correction-request:nd-0001-wrong-dob', NULL, NULL, NULL, NULL, NULL, 'synthetic-staff:records-clerk-001', '2026-03-05T11:00:00Z', true),
  ('northwind-synthetic', 'ndv-0003', 'nd-0005', 1, 'original', 'blob://documents/5d41ca3cd9573139dd74229c01d46ceec59a31ba3474e1e5291484df9016726c', '5d41ca3cd9573139dd74229c01d46ceec59a31ba3474e1e5291484df9016726c', 46, 'application/pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-provider:dr-lee', '2026-03-08T09:00:00Z', true),
  ('northwind-synthetic', 'ndv-0004', 'nd-0005', 2, 'statement-of-disagreement', 'blob://documents/50fd65fb153c9ef3d25f67aa5a60c8ad95fa6e219d589c8425e17fdcef8c4198', '50fd65fb153c9ef3d25f67aa5a60c8ad95fa6e219d589c8425e17fdcef8c4198', 69, 'application/pdf', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-patient:np-sam-porter', '2026-03-12T14:00:00Z', true),
  ('northwind-synthetic', 'ndv-0005', 'nd-0006', 1, 'original', 'blob://documents/0b6fff4cf15bc13effc8e91833c4bfd152bc0859d784c4c79d49b873f164c7b9', '0b6fff4cf15bc13effc8e91833c4bfd152bc0859d784c4c79d49b873f164c7b9', 57, 'application/pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-portal-intake', '2026-03-09T08:00:00Z', true),
  ('northwind-synthetic', 'ndv-0006', 'nd-0006', 2, 'esign-execution', 'blob://documents/616e704128a8e384212c470475d6322b30ff0f442a57c90baf2ff479f0ecf673', '616e704128a8e384212c470475d6322b30ff0f442a57c90baf2ff479f0ecf673', 55, 'application/pdf', 1, NULL, NULL, ARRAY['synthetic-patient:np-sam-porter']::text[], 'click-to-sign', '50d3081e5b15d9017a990eb7eaef4ad94da9f687a5c947a80bfb827d6b2af224', '2026-03-09T08:30:00Z', 'synthetic-esign-evidence:nesr-0001', 'synthetic-esign-rail', '2026-03-09T08:30:00Z', true),
  ('northwind-synthetic', 'ndv-0007', 'nd-0007', 1, 'original', 'blob://documents/06ae4729f024af4880f6487d8d9118975fd1d332eaba6d840bc24b9bf23c4b7b', '06ae4729f024af4880f6487d8d9118975fd1d332eaba6d840bc24b9bf23c4b7b', 56, 'application/pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-lab-gateway', '2026-03-11T10:00:00Z', true),
  ('riverbend-synthetic', 'rdv-0001', 'rd-0002', 1, 'original', 'blob://documents/00c6a735e51f552dd1c0a066ce1ae5abbe24dfe9f6196d6e31e99b0544d64ec3', '00c6a735e51f552dd1c0a066ce1ae5abbe24dfe9f6196d6e31e99b0544d64ec3', 52, 'application/pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-staff:rb-clerk-001', '2026-03-04T12:00:00Z', true)
ON CONFLICT (tenant_id, version_event_id) DO NOTHING;

INSERT INTO documents.document_search_index
  (tenant_id, document_id, version_no, doc_type, search_terms, partition_tags, segments, synthetic)
VALUES
  ('northwind-synthetic', 'nd-0001', 2, 'referral-summary', 'cardiology referral consult summary specialist', '{}'::text[], ARRAY['clinical']::text[], true),
  ('northwind-synthetic', 'nd-0005', 1, 'visit-note', 'annual physical visit note progress', '{}'::text[], ARRAY['clinical']::text[], true),
  ('northwind-synthetic', 'nd-0006', 2, 'consent-form', 'treatment consent authorization signed', '{}'::text[], ARRAY['consent']::text[], true),
  ('northwind-synthetic', 'nd-0007', 1, 'genetic-panel-result', 'hereditary panel genetic sequencing report', ARRAY['gipa-genetic']::text[], ARRAY['clinical']::text[], true),
  ('riverbend-synthetic', 'rd-0002', 1, 'visit-note', 'riverbend visit note record', '{}'::text[], ARRAY['clinical']::text[], true)
ON CONFLICT (tenant_id, document_id, version_no) DO UPDATE
SET doc_type = EXCLUDED.doc_type,
    search_terms = EXCLUDED.search_terms,
    partition_tags = EXCLUDED.partition_tags,
    segments = EXCLUDED.segments,
    synthetic = EXCLUDED.synthetic;

INSERT INTO documents.records_disclosure
  (tenant_id, disclosure_id, subject_person_ref, recipient_ref, purpose, requested_by,
   included_artifact_refs, excluded_out_of_scope_refs, excluded_genetic_refs,
   genetic_authorization_ref, genetic_written_evidence_ref, disclosed_at, closure_status,
   closure_evidence_ref, synthetic)
VALUES
  ('northwind-synthetic', 'ndd-0001', 'np-sam-porter', 'synthetic-auditor:state-board-0007', 'subpoena-audit', 'synthetic-staff:compliance-officer-001', ARRAY['blob://documents/688c67d0f2eb5fe5547c7833157fec21d8cdef9079287efe4e013015b2f2dba2', 'blob://documents/616e704128a8e384212c470475d6322b30ff0f442a57c90baf2ff479f0ecf673']::text[], '{}'::text[], ARRAY['blob://documents/06ae4729f024af4880f6487d8d9118975fd1d332eaba6d840bc24b9bf23c4b7b']::text[], NULL, NULL, '2026-03-15T00:00:00Z', 'closed-with-evidence', 'synthetic-disclosure-receipt:ndd-0001-auditor-ack', true),
  ('riverbend-synthetic', 'rdd-0001', 'rp-jordan-vale', 'synthetic-partner:rb-referral-0002', 'treatment', 'synthetic-staff:rb-clerk-001', ARRAY['blob://documents/00c6a735e51f552dd1c0a066ce1ae5abbe24dfe9f6196d6e31e99b0544d64ec3']::text[], '{}'::text[], '{}'::text[], NULL, NULL, '2026-03-16T00:00:00Z', 'transmitted', NULL, true)
ON CONFLICT (tenant_id, disclosure_id) DO UPDATE
SET closure_status = EXCLUDED.closure_status,
    closure_evidence_ref = EXCLUDED.closure_evidence_ref,
    synthetic = EXCLUDED.synthetic;
-- documents-records:generated:end
