-- WP-026 vendor registry seed (M07): the synthetic BAA inventory the runtime
-- egress guard reads, its versioned lifecycle log (the vendor projection is its
-- fold), the egress-decision activity feed (one allow + one block standing proof),
-- and the content-license gate rows. Generated from
-- modules/platform-integration/src/seed-data.ts (syntheticVendorRegistrySeedV1) via
-- renderVendorRegistrySeedSection; a drift test and the DB suite fail on divergence.
-- Regenerate only through the byte-faithful writer (WP-020 lesson). Depends on
-- 0017-vendor-registry.sql + 003-tenancy-seed.sql. Riverbend carries the opposite
-- BAA posture (a vendor with no executed BAA) as the standing cross-tenant proof.
-- vendor-registry:generated:begin
-- Generated by @practicehub/platform-integration renderVendorRegistrySeedSection from
-- syntheticVendorRegistrySeedV1. Regenerate on any seed change; the drift test
-- and the DB projection-sync test fail on divergence.
INSERT INTO platform_integration.vendor_event
  (tenant_id, vendor_id, version, kind, vendor_class, is_ai_vendor, enforcement_point,
   baa_status, baa_effective, baa_expiry, no_training_on_phi, zero_retention,
   permitted_categories, evidence_ref, approved_by, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'synthetic-ai-llm-vendor', 1, 'registered', 'voice-ai-llm', true, 'llm-api-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-ai-llm-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-ai-llm-vendor', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2027-01-05'::date, true, true, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-ai-llm-vendor-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-ai-uncovered', 1, 'registered', 'ai-general', true, 'ai-api-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-ai-uncovered-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-ai-uncovered', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2027-01-05'::date, false, true, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-ai-uncovered-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-cpaas-vendor', 1, 'registered', 'cpaas', false, 'message-send-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-cpaas-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-cpaas-vendor', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2027-06-05'::date, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-cpaas-vendor-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-labs-vendor', 1, 'registered', 'labs', false, 'lab-order-result-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-labs-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-labs-vendor', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2027-01-05'::date, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-labs-vendor-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-lapsed-vendor', 1, 'registered', 'fax', false, 'outbound-fax-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-lapsed-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-lapsed-vendor', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2026-03-05'::date, NULL, NULL, ARRAY['ID', 'CLIN']::text[], 'synthetic-baa:synthetic-lapsed-vendor-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-lapsed-vendor', 3, 'baa-lapsed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'synthetic-baa:lapsed-vendor-lapse', NULL, '2026-03-06T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-payments-vendor', 1, 'registered', 'payments', false, 'stripe-metadata-boundary', 'required', NULL, NULL, NULL, NULL, ARRAY['PAY', 'ID']::text[], 'synthetic-baa:synthetic-payments-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-payments-vendor', 2, 'baa-executed', NULL, NULL, NULL, 'executed', '2026-01-05'::date, '2027-01-05'::date, NULL, NULL, ARRAY['PAY', 'ID']::text[], 'synthetic-baa:synthetic-payments-vendor-executed', 'synthetic-compliance-officer', '2026-01-05T00:00:00Z'::timestamptz, true),
  ('riverbend-synthetic', 'synthetic-rb-vendor', 1, 'registered', 'cpaas', false, 'message-send-boundary', 'required', NULL, NULL, NULL, NULL, '{}'::text[], 'synthetic-baa:synthetic-rb-vendor-registered', 'synthetic-compliance-officer', '2026-01-02T00:00:00Z'::timestamptz, true)
ON CONFLICT (tenant_id, vendor_id, version) DO NOTHING;

INSERT INTO platform_integration.vendor
  (tenant_id, vendor_id, vendor_class, is_ai_vendor, enforcement_point, baa_status,
   baa_effective, baa_expiry, no_training_on_phi, zero_retention, permitted_categories,
   status, version, synthetic)
VALUES
  ('northwind-synthetic', 'synthetic-ai-llm-vendor', 'voice-ai-llm', true, 'llm-api-boundary', 'executed', '2026-01-05'::date, '2027-01-05'::date, true, true, ARRAY['ID', 'CLIN']::text[], 'active', 2, true),
  ('northwind-synthetic', 'synthetic-ai-uncovered', 'ai-general', true, 'ai-api-boundary', 'executed', '2026-01-05'::date, '2027-01-05'::date, false, true, ARRAY['ID', 'CLIN']::text[], 'active', 2, true),
  ('northwind-synthetic', 'synthetic-cpaas-vendor', 'cpaas', false, 'message-send-boundary', 'executed', '2026-01-05'::date, '2027-06-05'::date, false, false, ARRAY['ID', 'CLIN']::text[], 'active', 2, true),
  ('northwind-synthetic', 'synthetic-labs-vendor', 'labs', false, 'lab-order-result-boundary', 'executed', '2026-01-05'::date, '2027-01-05'::date, false, false, ARRAY['ID', 'CLIN']::text[], 'active', 2, true),
  ('northwind-synthetic', 'synthetic-lapsed-vendor', 'fax', false, 'outbound-fax-boundary', 'executed', '2026-01-05'::date, '2026-03-05'::date, false, false, ARRAY['ID', 'CLIN']::text[], 'suspended', 3, true),
  ('northwind-synthetic', 'synthetic-payments-vendor', 'payments', false, 'stripe-metadata-boundary', 'executed', '2026-01-05'::date, '2027-01-05'::date, false, false, ARRAY['PAY', 'ID']::text[], 'active', 2, true),
  ('riverbend-synthetic', 'synthetic-rb-vendor', 'cpaas', false, 'message-send-boundary', 'required', NULL, NULL, false, false, '{}'::text[], 'active', 1, true)
ON CONFLICT (tenant_id, vendor_id) DO UPDATE
SET vendor_class = EXCLUDED.vendor_class,
    is_ai_vendor = EXCLUDED.is_ai_vendor,
    enforcement_point = EXCLUDED.enforcement_point,
    baa_status = EXCLUDED.baa_status,
    baa_effective = EXCLUDED.baa_effective,
    baa_expiry = EXCLUDED.baa_expiry,
    no_training_on_phi = EXCLUDED.no_training_on_phi,
    zero_retention = EXCLUDED.zero_retention,
    permitted_categories = EXCLUDED.permitted_categories,
    status = EXCLUDED.status,
    version = EXCLUDED.version,
    synthetic = EXCLUDED.synthetic;

INSERT INTO platform_integration.content_license
  (tenant_id, license_id, content_family, status, effective, expiry, rights_ref, checksum, synthetic)
VALUES
  ('northwind-synthetic', 'synthetic-compendium-license', 'drug-compendium', 'lapsed', '2025-01-01'::date, '2026-01-01'::date, 'synthetic-license:compendium-permitted-use', 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', true),
  ('northwind-synthetic', 'synthetic-cpt-license', 'cpt', 'active', '2026-01-01'::date, '2027-01-01'::date, 'synthetic-license:cpt-permitted-use', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', true),
  ('riverbend-synthetic', 'synthetic-rb-cpt', 'cpt', 'pending', NULL, NULL, 'synthetic-license:rb-cpt-pending', 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc', true)
ON CONFLICT (tenant_id, license_id) DO UPDATE
SET content_family = EXCLUDED.content_family,
    status = EXCLUDED.status,
    effective = EXCLUDED.effective,
    expiry = EXCLUDED.expiry,
    rights_ref = EXCLUDED.rights_ref,
    checksum = EXCLUDED.checksum,
    synthetic = EXCLUDED.synthetic;

INSERT INTO platform_integration.egress_decision
  (tenant_id, decision_id, vendor_id, decision, phi_class, categories, reason,
   incident_opened, occurred_at, synthetic)
VALUES
  ('northwind-synthetic', 'synthetic-egress-allow-0001', 'synthetic-payments-vendor', 'allow', 'demographic', ARRAY['PAY', 'ID']::text[], 'permitted', false, '2026-03-15T09:00:00Z'::timestamptz, true),
  ('northwind-synthetic', 'synthetic-egress-block-0001', 'synthetic-labs-vendor', 'deny', 'PHI-restricted', ARRAY['GEN']::text[], 'category-not-permitted', true, '2026-03-15T09:05:00Z'::timestamptz, true),
  ('riverbend-synthetic', 'synthetic-rb-egress-block-0001', 'synthetic-rb-vendor', 'deny', 'PHI', ARRAY['ID', 'CLIN']::text[], 'baa-not-executed', true, '2026-03-15T09:10:00Z'::timestamptz, true)
ON CONFLICT (tenant_id, decision_id) DO NOTHING;
-- vendor-registry:generated:end
