-- WP-053 entitlements consume journal. Re-runnable. Unapplied until stack-grant.
CREATE SCHEMA IF NOT EXISTS entitlements;

CREATE TABLE IF NOT EXISTS entitlements.consumption (
  tenant_id text NOT NULL,
  consumption_id text NOT NULL,
  member_ref text NOT NULL,
  vintage_id text NOT NULL,
  sku_ref text NOT NULL,
  idempotency_key text NOT NULL,
  payer text NOT NULL CHECK (payer IN ('member','employer')),
  allowed_discount_cents integer NOT NULL CHECK (allowed_discount_cents >= 0),
  synthetic boolean NOT NULL,
  PRIMARY KEY (tenant_id, consumption_id),
  UNIQUE (tenant_id, idempotency_key),
  UNIQUE (tenant_id, member_ref, vintage_id, sku_ref)
);

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE entitlements.consumption ENABLE ROW LEVEL SECURITY;
ALTER TABLE entitlements.consumption FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON entitlements.consumption;
CREATE POLICY tenant_isolation ON entitlements.consumption
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'entitlements'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('consumption'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema entitlements: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
