-- WP-031 app-owned entitlement authority. External processor state is not representable.
CREATE SCHEMA IF NOT EXISTS membership_entitlements;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_membership_entitlements') THEN
    CREATE ROLE module_membership_entitlements NOLOGIN;
  END IF;
END $roles$;
GRANT module_membership_entitlements TO practicehub_app;
GRANT USAGE ON SCHEMA membership_entitlements TO module_membership_entitlements;
GRANT EXECUTE ON FUNCTION payments_ledger.is_entitlement_authority(text,text,text)
  TO module_membership_entitlements;

CREATE TABLE IF NOT EXISTS membership_entitlements.entitlement_event (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  entitlement_event_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('granted','reversed')),
  member_ref text NOT NULL,
  component_ref text NOT NULL,
  entitlement_kind text NOT NULL,
  authority_journal_id text NOT NULL,
  idempotency_key text NOT NULL,
  reversal_of_event_id text,
  occurred_at timestamptz NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, entitlement_event_id),
  UNIQUE (tenant_id, idempotency_key),
  FOREIGN KEY (tenant_id, reversal_of_event_id) REFERENCES membership_entitlements.entitlement_event (tenant_id, entitlement_event_id),
  CHECK ((event_type = 'granted' AND reversal_of_event_id IS NULL) OR (event_type = 'reversed' AND reversal_of_event_id IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS entitlement_one_reversal
  ON membership_entitlements.entitlement_event (tenant_id, reversal_of_event_id)
  WHERE reversal_of_event_id IS NOT NULL;

CREATE OR REPLACE FUNCTION membership_entitlements.assert_exact_reversal()
RETURNS trigger
LANGUAGE plpgsql
AS $reversal$
DECLARE
  original membership_entitlements.entitlement_event%ROWTYPE;
BEGIN
  IF NEW.event_type = 'granted' AND NOT payments_ledger.is_entitlement_authority(
    NEW.tenant_id, NEW.authority_journal_id, NULL
  ) THEN
    RAISE EXCEPTION 'entitlement grant % lacks app-ledger authority',
      NEW.entitlement_event_id USING ERRCODE = '23514';
  END IF;
  IF NEW.event_type <> 'reversed' THEN
    RETURN NEW;
  END IF;
  SELECT * INTO original
    FROM membership_entitlements.entitlement_event
   WHERE tenant_id = NEW.tenant_id AND entitlement_event_id = NEW.reversal_of_event_id;
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;
  IF original.event_type <> 'granted'
     OR original.member_ref <> NEW.member_ref
     OR original.component_ref <> NEW.component_ref
     OR original.entitlement_kind <> NEW.entitlement_kind
     OR original.authority_journal_id = NEW.authority_journal_id THEN
    RAISE EXCEPTION 'entitlement event % is not an exact authorized reversal of %',
      NEW.entitlement_event_id, NEW.reversal_of_event_id USING ERRCODE = '23514';
  END IF;
  IF NOT payments_ledger.is_entitlement_authority(
    NEW.tenant_id, NEW.authority_journal_id, original.authority_journal_id
  ) THEN
    RAISE EXCEPTION 'entitlement reversal % lacks exact app-ledger reversal authority',
      NEW.entitlement_event_id USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$reversal$;

DROP TRIGGER IF EXISTS entitlement_exact_reversal ON membership_entitlements.entitlement_event;
CREATE TRIGGER entitlement_exact_reversal
BEFORE INSERT ON membership_entitlements.entitlement_event
FOR EACH ROW EXECUTE FUNCTION membership_entitlements.assert_exact_reversal();
GRANT SELECT, INSERT ON membership_entitlements.entitlement_event TO module_membership_entitlements;
REVOKE UPDATE, DELETE ON membership_entitlements.entitlement_event FROM module_membership_entitlements;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE membership_entitlements.entitlement_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_entitlements.entitlement_event FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON membership_entitlements.entitlement_event;
CREATE POLICY tenant_isolation ON membership_entitlements.entitlement_event
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'membership_entitlements'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('entitlement_event'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema membership_entitlements: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
