-- WP-075 inventory: products, lots, units, dispense ties, recall drills.
CREATE SCHEMA IF NOT EXISTS inventory;
DO $roles$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'module_inventory') THEN
    CREATE ROLE module_inventory NOLOGIN;
  END IF;
END $roles$;
GRANT module_inventory TO practicehub_app;
GRANT USAGE ON SCHEMA inventory TO module_inventory;

CREATE TABLE IF NOT EXISTS inventory.product (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  product_ref text NOT NULL CHECK (product_ref ~ '^product:[a-z0-9][a-z0-9-]{7,63}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, product_ref)
);

CREATE TABLE IF NOT EXISTS inventory.lot (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  lot_ref text NOT NULL CHECK (lot_ref ~ '^lot:[a-z0-9][a-z0-9-]{7,63}$'),
  product_ref text NOT NULL CHECK (product_ref ~ '^product:[a-z0-9][a-z0-9-]{7,63}$'),
  expiry_date date NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, lot_ref),
  FOREIGN KEY (tenant_id, product_ref) REFERENCES inventory.product (tenant_id, product_ref)
);

CREATE TABLE IF NOT EXISTS inventory.unit (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  unit_ref text NOT NULL CHECK (unit_ref ~ '^unit:[a-z0-9][a-z0-9-]{7,63}$'),
  lot_ref text NOT NULL CHECK (lot_ref ~ '^lot:[a-z0-9][a-z0-9-]{7,63}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, unit_ref),
  FOREIGN KEY (tenant_id, lot_ref) REFERENCES inventory.lot (tenant_id, lot_ref)
);

CREATE TABLE IF NOT EXISTS inventory.dispense (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  dispense_ref text NOT NULL CHECK (dispense_ref ~ '^dispense:[a-z0-9][a-z0-9-]{7,63}$'),
  dispensed_on date NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, dispense_ref)
);

CREATE TABLE IF NOT EXISTS inventory.dispense_unit (
  tenant_id text NOT NULL,
  dispense_ref text NOT NULL,
  unit_ref text NOT NULL,
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, dispense_ref, unit_ref),
  UNIQUE (tenant_id, unit_ref),
  FOREIGN KEY (tenant_id, dispense_ref) REFERENCES inventory.dispense (tenant_id, dispense_ref),
  FOREIGN KEY (tenant_id, unit_ref) REFERENCES inventory.unit (tenant_id, unit_ref)
);

CREATE TABLE IF NOT EXISTS inventory.recall_unit (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  drill_ref text NOT NULL CHECK (drill_ref ~ '^drill:[a-z0-9][a-z0-9-]{7,63}$'),
  lot_ref text NOT NULL CHECK (lot_ref ~ '^lot:[a-z0-9][a-z0-9-]{7,63}$'),
  unit_ref text NOT NULL CHECK (unit_ref ~ '^unit:[a-z0-9][a-z0-9-]{7,63}$'),
  dispense_ref text CHECK (dispense_ref IS NULL OR dispense_ref ~ '^dispense:[a-z0-9][a-z0-9-]{7,63}$'),
  synthetic boolean NOT NULL CHECK (synthetic),
  PRIMARY KEY (tenant_id, drill_ref, unit_ref),
  FOREIGN KEY (tenant_id, lot_ref) REFERENCES inventory.lot (tenant_id, lot_ref),
  FOREIGN KEY (tenant_id, unit_ref) REFERENCES inventory.unit (tenant_id, unit_ref)
);

GRANT SELECT, INSERT ON inventory.product, inventory.lot, inventory.unit, inventory.dispense, inventory.dispense_unit, inventory.recall_unit TO module_inventory;
REVOKE UPDATE, DELETE ON inventory.product, inventory.lot, inventory.unit, inventory.dispense, inventory.dispense_unit, inventory.recall_unit FROM module_inventory;
-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE inventory.dispense ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.dispense FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.dispense;
CREATE POLICY tenant_isolation ON inventory.dispense
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE inventory.dispense_unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.dispense_unit FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.dispense_unit;
CREATE POLICY tenant_isolation ON inventory.dispense_unit
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE inventory.lot ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.lot FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.lot;
CREATE POLICY tenant_isolation ON inventory.lot
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE inventory.product ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.product FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.product;
CREATE POLICY tenant_isolation ON inventory.product
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE inventory.recall_unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.recall_unit FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.recall_unit;
CREATE POLICY tenant_isolation ON inventory.recall_unit
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

ALTER TABLE inventory.unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.unit FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON inventory.unit;
CREATE POLICY tenant_isolation ON inventory.unit
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'inventory'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('dispense', 'dispense_unit', 'lot', 'product', 'recall_unit', 'unit'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema inventory: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
