-- WP-011 platform_core jurisdiction migration.
-- Contract: docs/contracts/jurisdiction-resolver.md (FROZEN). Architecture: ADR-005 Decision 5.
-- Idempotent: safe to re-apply; the DB suite re-applies it as its idempotency proof.
-- Rollback: modules/platform-core/migrations/0002-jurisdiction.rollback.sql.
-- The section between the rls:generated markers is emitted by
-- renderRlsMigrationSection('platform_core', jurisdictionRlsSpecs, platformCoreRlsSpecs);
-- a drift test compares this file against a fresh emission.

-- Versioned, counsel-owned jurisdiction rule packs (jurisdiction x version).
-- Statutory reference data: law is tenant-independent, so these two tables are
-- declared platform-global in the RLS spec with a written justification.
-- Prior versions are retained; reverting a pack drops its newest version.
CREATE TABLE IF NOT EXISTS platform_core.jurisdiction_rule_pack (
  jurisdiction text NOT NULL CHECK (
    jurisdiction ~ '^[A-Z]{2}$' OR jurisdiction IN ('floor', 'unknown')
  ),
  version integer NOT NULL CHECK (version >= 1),
  status text NOT NULL CHECK (status IN ('draft', 'counsel-signed')),
  counsel_signoff_ref text,
  change_control_ref text NOT NULL CHECK (change_control_ref ~ '^[a-z0-9][a-z0-9-]{0,127}$'),
  synthetic boolean NOT NULL,
  PRIMARY KEY (jurisdiction, version),
  -- EW-025: counsel sign-off is evidenced, never asserted.
  CONSTRAINT jurisdiction_pack_signed_requires_ref
    CHECK (status <> 'counsel-signed' OR counsel_signoff_ref IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS platform_core.jurisdiction_rule (
  jurisdiction text NOT NULL,
  pack_version integer NOT NULL,
  topic text NOT NULL CHECK (
    topic IN (
      'recording-consent', 'chd-rights', 'genetic-authorization', 'records-consent',
      'erx-epcs-pdmp', 'telehealth-licensure', 'auto-renewal', 'retention',
      'biometrics', 'ai-disclosure', 'cpom', 'minors-part2'
    )
  ),
  obligations jsonb NOT NULL CHECK (jsonb_typeof(obligations) = 'array'),
  scalars jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(scalars) = 'object'),
  source_ref text NOT NULL,
  synthetic boolean NOT NULL,
  PRIMARY KEY (jurisdiction, pack_version, topic),
  CONSTRAINT jurisdiction_rule_pack_exists
    FOREIGN KEY (jurisdiction, pack_version)
    REFERENCES platform_core.jurisdiction_rule_pack (jurisdiction, version)
    ON DELETE CASCADE
);

-- R6-SR-001 (M01 slice): patient physical-location facts captured at booking
-- and re-confirmed at visit start for a regulated-action context. When they
-- differ, BOTH records are retained with their timestamps -- append-only by
-- grant (UPDATE/DELETE revoked below), so divergence can never be papered over.
-- state_code NULL = unknown; the resolver then applies the safe defaults.
CREATE TABLE IF NOT EXISTS platform_core.location_capture (
  tenant_id text NOT NULL REFERENCES platform_core.tenant (tenant_id),
  capture_id text NOT NULL CHECK (capture_id ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  context_ref text NOT NULL CHECK (context_ref ~ '^[a-z0-9][a-z0-9-]{0,127}$'),
  stage text NOT NULL CHECK (stage IN ('booking', 'visit-start')),
  state_code text CHECK (state_code ~ '^[A-Z]{2}$'),
  captured_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL,
  synthetic boolean NOT NULL,
  PRIMARY KEY (tenant_id, capture_id)
);

-- Runtime posture: the statutory registry is read-only for the module role
-- (rule changes arrive as change-controlled pack versions via seeds, never
-- runtime writes); location capture is append-only (divergence retention).
-- 0001's schema-wide GRANT re-runs before this file on every migrate pass,
-- so these REVOKEs re-apply the posture deterministically each pass.
REVOKE INSERT, UPDATE, DELETE
  ON platform_core.jurisdiction_rule_pack, platform_core.jurisdiction_rule
  FROM module_platform_core;
REVOKE UPDATE, DELETE ON platform_core.location_capture FROM module_platform_core;

-- rls:generated:begin
-- Generated by @practicehub/platform-core generateRlsDdl/generateRlsCoverageGuard.
-- Regenerate via renderRlsMigrationSection; the drift test fails on divergence.
ALTER TABLE platform_core.jurisdiction_rule ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_core.jurisdiction_rule FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON platform_core.jurisdiction_rule;
-- platform-global: Statutory jurisdiction rule content; law is tenant-independent reference data (ADR-005 Decision 5)
CREATE POLICY tenant_isolation ON platform_core.jurisdiction_rule
  USING (true)
  WITH CHECK (true);

ALTER TABLE platform_core.jurisdiction_rule_pack ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_core.jurisdiction_rule_pack FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON platform_core.jurisdiction_rule_pack;
-- platform-global: Statutory jurisdiction rule content; law is tenant-independent reference data (ADR-005 Decision 5)
CREATE POLICY tenant_isolation ON platform_core.jurisdiction_rule_pack
  USING (true)
  WITH CHECK (true);

ALTER TABLE platform_core.location_capture ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_core.location_capture FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON platform_core.location_capture;
CREATE POLICY tenant_isolation ON platform_core.location_capture
  USING (tenant_id = current_setting('practicehub.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('practicehub.tenant_id', true));

DO $coverage$
DECLARE
  offender text;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO offender
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'platform_core'
     AND c.relkind = 'r'
     AND (NOT c.relrowsecurity
          OR NOT c.relforcerowsecurity
          OR c.relname NOT IN ('jurisdiction_rule', 'jurisdiction_rule_pack', 'legal_entity', 'location', 'location_capture', 'synthetic_tenant', 'tenant', 'tenant_config'));
  IF offender IS NOT NULL THEN
    RAISE EXCEPTION 'rls coverage failure in schema platform_core: %', offender;
  END IF;
END
$coverage$;
-- rls:generated:end
